### ISSUE TITLE
Wrong order of returned fields when function is used in select list

### ISSUE THREAD

**Issue by galkk** [opendistro-for-elasticsearch/sql#100]
When using function in select list, the order of fields in returned csv doesn't match the order in the query

```
POST _opendistro/_sql?format=csv
{
  "query": "SELECT ip, utc_time, date_format(utc_time, 'dd-MM-YYYY') date from kibana_sample_data_logs"
}
```

Expected field order: ip, utc_time, date
Actual field order: date,ip,utc_time
22-07-2018,157.4.76.38,2018-07-22T12:23:52.803Z

**Comment by dai-chen** [comment]
JDBC format seems able to handle this case. So this should be fixed once we merge the different code paths to one in https://github.com/opendistro-for-elasticsearch/sql/issues/148.
