### ISSUE TITLE
Add "opendistro.sql.delete.enabled" setting

### ISSUE THREAD

**Issue by fbaligand** [opendistro-for-elasticsearch/sql#1003]
Hi,

This would be great to add a "opendistro.sql.delete.enabled" setting here:
https://opendistro.github.io/for-elasticsearch-docs/docs/sql/settings/

Thanks to this, "DELETE" command can be disabled and SQL commands (especially from ODBC/JDBC drivers) can be strictly read-only queries.

**Comment by dai-chen** [comment]
Hi @fbaligand, I think security plugin is a better fit for the new setting you're proposing. You can create a role with read-only permission and then users in the role can only run queries. Thanks!

**Comment by fbaligand** [comment]
Yes, that’s quite relevant. 
To be transparent, I use readonlyrest security plugin. And it seems that sql queries bypass readonlyrest security checks.

**Comment by dai-chen** [comment]
> Yes, that’s quite relevant.
> To be transparent, I use readonlyrest security plugin. And it seems that sql queries bypass readonlyrest security checks.

I don't remember we have this issue. Could you provide more details? Such as given which permissions, your readonly user can still run DELETE command on an index. Thanks!

**Comment by fbaligand** [comment]
Hi @dai-chen,

So here's some details about my case:
- I use readonlyrest 1.26.1 (last version) on Elasticsearch 7.9
- my readonlyrest.yml is:
``` yaml
readonlyrest:
    access_control_rules:
    - name: sql users
      type: allow
      auth_key: sql:sql
      actions: ["indices:data/read/*", "cluster:monitor/main"]
```
- When I do this SQL query: `DELETE index1 WHERE field1='value1';`, the line is deleted and I have these server logs:
```
[2021-01-25T09:12:34,681][INFO ][c.a.o.s.l.p.RestSqlAction] [DESKTOP-8QK15CF] [9d674352-04f1-4ffd-b143-fe6742b72eca] Incoming request /_opendistro/_sql?format=jdbc: 

DELETE fabien WHERE field1='value1'
```
- I don't see any readonlyrest audit log line that says if action is allowed or forbidden, as if security is bypassed.
- normally, I should see this kind of log line:
`[2021-01-26T08:57:18,504][INFO ][t.b.r.a.l.AccessControlLoggingDecorator] [DESKTOP-8QK15CF] [ALLOWED by { name: 'sql users', policy: ALLOW, rules: [auth_key,actions] req={  ID:1529897497-1569146382#79,  TYP:MainRequest,  CGR:N/A,  USR:sql,  BRS:true,  KDX:null,  ACT:cluster:monitor/main,  OA:127.0.0.1/32,  XFF:null,  DA:127.0.0.1/32,  IDX:<N/A>,  MET:GET,  PTH:/,  CNT:<N/A>,  HDR:Accept=application/json, Authorization=<OMITTED>, Connection=Keep-Alive, Host=localhost:9200, User-Agent=openes-jdbc/1.11.0.0 (Java 11.0.4), content-length=0,  HIS:[Accept requests from users in admin group-> RULES:[groups->false]], [Accept requests from kibana-> RULES:[groups->false]], [Kibana read users-> RULES:[groups->false]], [Kibana write users-> RULES:[groups->false]], [sql users-> RULES:[auth_key->true, actions->true] RESOLVED:[user=sql]],  }`
- by the way, with a `SELECT` SQL query, I don't see readonlyrest audit log line too. I see audit log line only for "cluster:monitor/main" action (for my `sql` user)

**Comment by penghuo** [comment]
I do the test in AWS Elaticsearch 7.9.

Role: sql-readonly
 cluster:monitor/main
 indices:data/read/*
User: sql-test mapping to sql-readonly

```
DELETE employee
PUT employee/_doc/1
{
  "id": 1
}
PUT employee/_doc/2
{
  "id": 2
}
```

* Query works as expected
```
POST /_opendistro/_sql
{
  "query": """
    SELECT * FROM employee WHERE id = 1
  """
}

{
  "schema": [{
    "name": "id",
    "type": "long"
  }],
  "total": 1,
  "datarows": [[1]],
  "size": 1,
  "status": 200
}
```

* DELETE throw exception
```
POST /_opendistro/_sql/
{
  "query": """
    DELETE employee WHERE id = 1
  """
}

{
  "error": {
    "reason": "Error occurred in Elasticsearch engine: no permissions for [indices:data/write/delete/byquery] and User [name=sql-test, backend_roles=[], requestedTenant=__user__]",
    "details": """org.elasticsearch.ElasticsearchSecurityException: no permissions for [indices:data/write/delete/byquery] and User [name=sql-test, backend_roles=[], requestedTenant=__user__]
For more details, please send request for Json format to see the raw response from elasticsearch engine.""",
    "type": "ElasticsearchSecurityException"
  },
  "status": 403
}
```

**Comment by penghuo** [comment]
Could you try to verify the permission without using SQL? Actually, SQL use Elasticsearch [delete by query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html), e.g, you can verify the permission with the following query.

```
POST employee/_delete_by_query
{
  "size" : 1000,
  "query" : {
    "bool" : {
      "must" : [
        {
          "term" : {
            "id" : {
              "value" : 1,
              "boost" : 1.0
            }
          }
        }
      ],
      "adjust_pure_negative" : true,
      "boost" : 1.0
    }
  },
  "_source" : false
}

{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for [indices:data/write/delete/byquery] and User [name=sql-test, backend_roles=[], requestedTenant=__user__]"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for [indices:data/write/delete/byquery] and User [name=sql-test, backend_roles=[], requestedTenant=__user__]"
  },
  "status" : 403
}
```

**Comment by fbaligand** [comment]
Hi @penghuo ,

Well, as explained in my previous comment, my security plugin is [readonlyrest](https://readonlyrest.com/), not Open Distro for Elasticsearch security plugin.
I understand that "Open Distro for Elasticsearch security plugin" process nicely read/delete rights for SQL queries.

**Comment by penghuo** [comment]
Make sense, create the #1008 to tracking this.
Could you send the PR to add the opendistro.sql.delete.enabled setting?

**Comment by fbaligand** [comment]
Hi,

Nice to see that you think it makes sense.
Concerning PR, honestly, I don't know how to implement the feature.

**Comment by dai-chen** [comment]
Track in 1008 and will create issue in new OpenSearch repo soon.
