### ISSUE TITLE
Incorrect SQL returns "NullPointerException"

### ISSUE THREAD

**Issue by galkk** [opendistro-for-elasticsearch/sql#102]
Typo in the query returns NullPointerException instead of sometning more meaningful
```
POST _opendistro/_sql?format=csv
{
  "query": "SELECT ipFROM kibana_sample_data_logs"
}
```

Output:
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "",
    "type": "NullPointerException"
  },
  "status": 400
}

**Comment by dai-chen** [comment]
Need better wrong message here too: https://github.com/opendistro-for-elasticsearch/sql/issues/127. The "Failed to parse SqlExpression of type class com.alibaba.druid.sql.ast.expr.SQLBooleanExpr. expression value: xTRUE" is not very clear and expose internal implementation class.

**Comment by dai-chen** [comment]
Collecting more similar issue in https://github.com/opendistro-for-elasticsearch/sql/issues/62 and https://github.com/opendistro-for-elasticsearch/sql/issues/96.

**Comment by dai-chen** [comment]
We've introduced a new ANTLR parser with clearly specified grammar. For now the FROM clause is required because we don't support this and throw NPE as reported in this case.
