### ISSUE TITLE
[Workbench] Query workbench does not function correctly with SQL new engine

### ISSUE THREAD

**Issue by davidcui-amzn** [opendistro-for-elasticsearch/sql#1029]
Output results for simple queries in workbench do not give correct output with SQL new engine enabled. 

Output for running `SELECT * FROM kibana_sample_data_ecommerce` in Kibana 7.10.0 and 7.10.2 with new engine disabled:

![Screen Shot 2021-02-04 at 10 46 39 AM](https://user-images.githubusercontent.com/53581635/106944275-3bad0d80-66db-11eb-99f1-483fa190f129.png)

vs. output in Kibana 7.10.2 with new engine enabled:

![Screen Shot 2021-02-04 at 10 50 11 AM](https://user-images.githubusercontent.com/53581635/106944342-51223780-66db-11eb-8162-365cee6e6878.png)

**Comment by chloe-zh** [comment]
Located the issue: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/workbench/public/components/Main/main.tsx#L118 
JSON parse failed to parse `keyword`, `array` types

**Comment by chloe-zh** [comment]
Update: this issue relates to the changes in array type in new engine. In the new engine, the result only takes the first element from array, so it turns out no longer an expandable field but a plain field.
