### ISSUE TITLE
New release questions

### ISSUE THREAD

**Issue by dpgaspar** [opendistro-for-elasticsearch/sql#1046]
Hi @dai-chen,

First of all, big thanks for your support.

I have a couple of questions regarding the new release. ODFE 1.13 will have the new SQL engine turned on.

- Is there a way for a user to revert back to the previous SQL engine, HTTP API endpoint?
- Is it possible to get information about what "version" of the SQL endpoint is a cluster running on?
- Do you have any ETA for 1.13?

I have other technical questions regarding AWS ES and opendistro, but maybe this is not the proper channel?

**Comment by dai-chen** [comment]
Hi @dpgaspar , thanks for reaching out to us! Please find the answer to your questions inlined. Thanks!

> Is there a way for a user to revert back to the previous SQL engine, HTTP API endpoint?

For features not added to new engine, your query will fall back and handled by old engine. In this way, ideally, user should be unaware of this switch: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/dev/NewSQLEngine.md#32-limitations

If user wants to turn off new engine, they can change the plugin setting: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/dev/NewSQLEngine.md#33-what-if-something-wrong

> Is it possible to get information about what "version" of the SQL endpoint is a cluster running on?

We've been thinking about versioning. But based on our strategy of back-compatibility and fall back, we didn't add version info. For now, user can only figure out which engine handled their queries by log as explained in the first link above. If you feel necessary, could you share your use case in which version info is required?

> Do you have any ETA for 1.13?

The release process is going on and should be available soon.

**Comment by dpgaspar** [comment]
> We've been thinking about versioning. But based on our strategy of back-compatibility and fall back, we didn't add version info. For now, user can only figure out which engine handled their queries by log as explained in the first link above. If you feel necessary, could you share your use case in which version info is required?

If there is some compatibility decision a python DBAPI has to make. For example, on elasticsearch-dbapi when implementing SQLAlchemy `get_columns` the api goes directly to Elasticsearch (does not use SQL endpoint) so that we can fetch keyword fields, since on the current (previous?) implementation we are not able to GROUP BY non keyword fields. 

Not an issue because I figure this will still work on the new version (need to make tests run on both SQL engine versions) if it allows using keyword fields, example: `SELECT count(*), col1.keyword from index1 GROUP BY col1.keyword`

**Comment by dai-chen** [comment]
Hi @dpgaspar , we will recommend `SHOW/DESCRIBE` rather than get mapping from Elasticsearch directly. `keyword` in multi-field is one example which is present in ES mapping though we want to hide from customer view. You may not have the access to `.keyword` field due to a recent change: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/dev/NewSQLEngine.md#312-syntax-and-semantic

This is also how other BI tool interacts with our plugin. In this way, we also guarantee that `SELECT *` returns same columns as `DESCRIBE`.
