### ISSUE TITLE
Feature request, support comments

### ISSUE THREAD

**Issue by dpgaspar** [opendistro-for-elasticsearch/sql#1051]
Hi,

This is a feature request to support comments on ES SQL. The majority of database engines that use/accept SQL support it.

It's part of the SQL ANSI 1992

```
<comment> ::=
              <comment introducer> [ <comment character>... ] <newline>

<comment character> ::=
              <nonquote character>
              | <quote>

<comment introducer> ::= <minus sign><minus sign>[<minus sign>...]
```

Example:
``` sql
-- Cool query bellow
SELECT col1, col1 FROM table1
WHERE col1 = 'data1'
-- Cool query above
```

It has several use cases, a couple of examples:

- The user being able to save and share complex queries and annotate them.
- A system can "tag" a query, and this tag is used by external subsystems that can take decisions on it's base.

**Comment by dai-chen** [comment]
@dpgaspar Thanks for reporting the issue! This seems useful for our Query Workbench too. Will look into this.

**Comment by dai-chen** [comment]
@dpgaspar I just verified that this is already supported in the new SQL engine, including line comments, block comments and inline comment. You can expect this in the upcoming ODFE 1.13 release or test by enabling new engine manually in old version. Thanks!

Old engine:

```
POST _opendistro/_sql
{
  "query": """
    -- before
    SELECT 123
  """
}
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Query must start with SELECT, DELETE, SHOW or DESCRIBE: -- before     SELECT 123",
    "type": "SQLFeatureNotSupportedException"
  },
  "status": 400
}
```

New engine:

```
POST _opendistro/_sql
{
  "query": """
    -- before
    /*
     select 'a'
    */
    SELECT 123 -- inline
    -- after
    /*
     select 'a'
     select 'b'
    */
  """
}
{
  "schema": [
    {
      "name": "123",
      "type": "integer"
    }
  ],
  "datarows": [
    [
      123
    ]
  ],
  "total": 1,
  "size": 1,
  "status": 200
}
```

**Comment by dai-chen** [comment]
This seems not documented. Will add once confirmed.

**Comment by dpgaspar** [comment]
Awesome! closing this issue now
