### ISSUE TITLE
Backticks not supported for nested fields

### ISSUE THREAD

**Issue by dirkdaems** [opendistro-for-elasticsearch/sql#1060]
We tried to use the JDBC driver with Tableau. According to the docs (https://github.com/opendistro-for-elasticsearch/sql-jdbc/blob/master/docs/tableau.md) it is recommended to use the MySQL dialect.
When doing so, backticks are used as identifier quote characters. It looks like they are handled correct for tables(indices) and fields, but not for nested fields.
For example, this works:
``SELECT `t`.agent.ephemeral_id FROM `test` as t``
but, this doesn't:
``SELECT `t`.`agent.ephemeral_id` FROM `test` as t``
Error:
`
{
"error": {
"reason": "Invalid SQL query",
"details": "Field [t.`agent.ephemeral_id`] cannot be found or used here.",
"type": "SemanticAnalysisException"
},
"status": 400
}
`

**Comment by dirkdaems** [comment]
@dai-chen OpenDistro SQL version was 1.6.0.0.

**Comment by chloe-zh** [comment]
Hi @dirkdaems  this is one of the limitation of the old query engine. The old engine uses the old druid parser, and it is a little tricky to enable it to parse the backticks quoted identifiers. We were able to support the flat fields quoted with backticks, and also include the case you mentioned like ``` `t`.agent.ephemeral_id```, where only the index is quoted, but sadly we were not able to support the case where both indexname and field (for both flat and nested) are quoted. 

However we have released the new engine which has no issue with parsing the backticks quoted identifiers. It should be working well once the nested field is fully supported in our new engine. Currently it's available in the latest version of ODFE-SQL. New engine details: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/dev/NewSQLEngine.md

**Comment by penghuo** [comment]
Verified on ODFE 1.13
```
PUT my-index-000001/_doc/1
{
  "agent.ephemeral_id": "1"
}
POST _opendistro/_sql
{
  "query": """
  SELECT `t`.`agent.ephemeral_id` FROM `my-index-000001` as t
  """
}

{
  "schema": [
    {
      "name": "agent.ephemeral_id",
      "type": "text"
    }
  ],
  "datarows": [
    [
      "1"
    ]
  ],
  "total": 1,
  "size": 1,
  "status": 200
}
```
