### ISSUE TITLE
Response ERROR "No type found for field: XXX" when mapping does not contains the field while the doc does

### ISSUE THREAD

**Issue by chyun** [opendistro-for-elasticsearch/sql#1065]
I hive wrote some data into elasticsearch. The data contains a field "inbuilt_meta.event_type", but the value is null(the field is very important althought most of the record contains null value). The situation is the mapping of the index does not contains the field "inbuilt_meta.event_type", but the doc contains the field "inbuilt_meta.event_type" with value null.
when I input "select * from index", I got response
{ "error": { "type": "IllegalStateException", "reason": "There was internal problem at backend", "details": "No type found for field: inbuilt_meta.event_type." }, "status": 503 }
I use elasticsearch 7.10.2 and opendistro-sql 1.13.1

**Comment by dai-chen** [comment]
@chyun Thanks for reporting the issue! Could you share the index mapping and some data for our investigation?

**Comment by chyun** [comment]
```
index mapping:
{
  "sample" : {
    "mappings" : {
      "properties" : {
        "inbuilt_meta" : {
          "properties" : {
            "happen_timestamp" : {
              "type" : "long"
            },
          }
        },
        "account" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        }
      }
    }
  }
}

sample data:
data1:
"inbuilt_meta" : {
    "happen_timestamp" : 1614935865586,
    "event_type" : null,
},
"account" : "zous-001017"

data2:
"inbuilt_meta" : {
    "happen_timestamp" : 1614935865583,
    "event_type" : null
},
"account" : "7b32795322e5",
```

**Comment by dai-chen** [comment]
Thanks for the info. Debugging from my side.

**Comment by dai-chen** [comment]
I can reproduce the issue as follows:

```
PUT sample
{
  "mappings" : {
    "properties" : {
      "inbuilt_meta" : {
        "properties" : {
          "happen_timestamp" : {
            "type" : "long"
          }
        }
      },
      "account" : {
        "type" : "text",
        "fields" : {
          "keyword" : {
            "type" : "keyword",
            "ignore_above" : 256
          }
        }
      }
    }
  }
}

POST sample/_doc
{
  "inbuilt_meta" : {
    "happen_timestamp" : 1614935865586,
    "event_type" : null
  },
  "account" : "zous-001017"
}

POST _opendistro/_sql
{
  "query": """
    SELECT * FROM sample
  """
}
```

**Comment by dai-chen** [comment]
@chyun The error is because all `event_type` is null and Elasticsearch is unable to infer its type. In this case, it's absent in index mapping and caused the type not found error. You need to either give its type in PUT mapping request or have at least one document has non-null value so that Elasticsearch can add it to the index mapping on the fly. Thanks!

**Comment by chyun** [comment]
@dai-chen thanks. I can fix this by PUT mapping request. But if the project can process this case as UNDEFINED/ExprNullValue would be better.

**Comment by dai-chen** [comment]
@chyun yeah, for now the problem is our analyzer needs to do strict type check. we maybe able to let this work if users don't select that field specifically (like your `SELECT *`). But when they do `SELECT inbuilt_meta.event_type`, semantic analysis error would be thrown due to the field missing in index mapping.

**Comment by chyun** [comment]
@dai-chen thanks
