### ISSUE TITLE
AWS Elasticsearch Cluster ODBC Connection error: Failed to establish connection to DB.

### ISSUE THREAD

**Issue by ser0c** [opendistro-for-elasticsearch/sql#1069]
Hi,

We are trying to connect to an AWS Elasticsearch Cluster (v 7.9) using the odbc driver installed from opendistro-sql-odbc-1.13.0.0-macos-x64 (we have also tried testing using a compiled version).  We also tried on Windows with the same version.

We cannot seem to connect and we always get back "Failed to establish connection to DB."

Looking at the plugins for the aws cluster (_cat/plugins?v) we see
`name                             component                         version
28ff4b36fdcce75ff9b15594ef96b215 opendistro_sql                    x.x.x.x`

We can also perform queries using curl
`_opendistro/_sql' -k -H 'Content-Type: application/json' -d '{"query": "SELECT * FROM kibana_sample_data_logs LIMIT 10"}'` 

We configured the DSN as follows (on Mac)
`[ODFEAWSES]
Driver               = /Library/ODBC/odfe-sql-odbc/bin/libodfesqlodbc.dylib
Description          = ODFE SQL ODBC DSN
Host                 = https://search-addressxyz-west-1.es.amazonaws.com
Port                 = 443
Auth                 = BASIC
User                 = admin
Password             = {{password}}
UseSSL               = 1
HostnameVerification = 0
LogLevel             = ES_ALL
LogOutput            = /tmp/driverlogs`

We have attached the windows log for reference
[mylog_odbcad32_3988.log](https://github.com/opendistro-for-elasticsearch/sql/files/6104864/mylog_odbcad32_3988.log)

Is there anything we are doing wrong?  Can you help?

Thanks.

**Comment by dai-chen** [comment]
Thanks for reporting the issue! In your log file attached, I don't see any error. Is that the only driver log? Any more info you can provide from your side?

**Comment by ser0c** [comment]
Hi, thanks for responding.

The log file that I attached stops there, there is no more output.

Additional information for our test client:
Windows 10, Version 1703, OS Build 15063.540
ODBC Data Source Administrator+ Driver Manager = version 10.0.15063.0
OFDE SQL ODBC DRIVER = version 1.13.00.00

We configure the DSN as shown in the attached image.
<img width="940" alt="dsn config" src="https://user-images.githubusercontent.com/80102782/110552660-a5339800-812f-11eb-87dd-bfd80013ded4.png">

We configured the log level to LOG_ALL.

We are testing against AWS Elasticsearch Cluster version 7.9.

We perform testing - so far - using the "Test" button in the Elasticsearch ODBC Driver DSN Setup.

I have attached the latest log from our testing, this seems to show more information.

We tested with Hostname verification off and on (as shown in the log files).
[mylog_odbcad32_3384.hv_on.log](https://github.com/opendistro-for-elasticsearch/sql/files/6112089/mylog_odbcad32_3384.hv_on.log)
[mylog_odbcad32_3384.hv_off.log](https://github.com/opendistro-for-elasticsearch/sql/files/6112090/mylog_odbcad32_3384.hv_off.log)

Hope this helps.  If you would like us to test anything else, or share any more info, please just ask.

**Comment by dai-chen** [comment]
Thanks for the info! Will try it out later from my side.

**Comment by chloe-zh** [comment]
I wonder if it's possible because the read/write permission of odbcinst.ini and odbc.ini files for the odbc driver is not granted to the current user. Since I personally came across this situation before. And it worked after I changed these two files to readable and writable.

**Comment by ser0cla** [comment]
Hi,
We assume that on Windows, we need to modify the following registry permissions (please correct if we are not correct :-)):
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\ODBC\ODBCINST.INI
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\ODBC\ODBC.INI
Computer\HKEY_CURRENT_USER\Software\ODBC\ODBC.INI

We modified the permissions and gave all read/write and made sure we restarted just to double-check.

The logs still look pretty much the same, as per the attached.
[mylog_odbcad32_2008.log](https://github.com/opendistro-for-elasticsearch/sql/files/6158652/mylog_odbcad32_2008.log)

**Comment by dai-chen** [comment]
Found "The SQL plugin must be installed in order to use this driver" in your logs. This seems related to https://github.com/opendistro-for-elasticsearch/sql/issues/1078

**Comment by dai-chen** [comment]
Duplicate and will track in issue 1078.
