### ISSUE TITLE
nested query sql not _score 

### ISSUE THREAD

**Issue by lengrongfu** [opendistro-for-elasticsearch/sql#1071]
I have the following query statement. The results after my query cannot be sorted according to the score. I found that the score_mode is none after checking the DSL. Can I set it to make it possible to sort by the score?
![image](https://user-images.githubusercontent.com/15009201/110748422-a6bda700-827a-11eb-96d8-fc09caaff23f.png)
![image](https://user-images.githubusercontent.com/15009201/110748453-b2a96900-827a-11eb-889f-1531768b4c17.png)

**Comment by dai-chen** [comment]
Thanks for reporting the issue! I checked Elasticsearch doc and found `score_mode` means how to combine scores. As our doc shows, `ORDER BY _score` is translated to `sort` section in DSL? Reference: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/beyond/fulltext.rst#score-query. Did you see your result set is not sorted by score?

**Comment by lengrongfu** [comment]
@dai-chen yes, the result is not score。
![image](https://user-images.githubusercontent.com/15009201/110888463-34ef6700-8327-11eb-9165-f15306a95550.png)
![image](https://user-images.githubusercontent.com/15009201/110888511-4afd2780-8327-11eb-955c-9251aba095c4.png)

**Comment by dai-chen** [comment]
@lengrongfu Sorry for the delay! Could you share your test data (index mapping and several docs)?

**Comment by lengrongfu** [comment]
Thanks ！！！
I have solved it, extract the nested type field as an object, and then it can be sorted by the score when searching.
