### ISSUE TITLE
Help - Request to unblock the issue when generating windows ODBC.msi installable file for 1.11.0

### ISSUE THREAD

**Issue by CuriousQA** [opendistro-for-elasticsearch/sql#1085]
Due to existing sql plugin issue in 1.13.0, I want to install 1.11.0 ODBC .msi in my Windows 10 system. I have downloaded the source code 1.11.0 to generate the ODBC using the instructions in the BUILD. I installed JAVA 12, Visio 2019 and Cmake as part of this. After working on to create a new project in Visio studio 2019, I navigated to Tools --> Command Line --> Developer PowerShell.  I set the path of the developer Powershell to ODBC folder(C:\Users\abc\Downloads\sql-1.11.0.0\sql-odbc) and executed build_win_release64.ps1
![image](https://user-images.githubusercontent.com/33165402/113518395-b5cb0880-954b-11eb-8518-e9459fde2f87.png)

However after this, I encounter the following error

_-- Building for: NMake Makefiles
-- Found Git: C:/Users/abc/AppData/Local/Programs/Git/cmd/git.exe (found version "2.19.1.windows.1")
-- TARGET_ARCH not specified; inferring host OS to be platform compilation target
-- Building AWS libraries as shared objects
-- Generating windows build config
-- Building project version: 1.8.177
CMake Error at CMakeLists.txt:7 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/abc/Downloads/sql-1.11.0.0/sql-odbc/build/aws-sdk/build/.deps/CMakeFiles/CMakeOutput.log".
CMake Error at CMakeLists.txt:218 (message):
  Failed to configure third-party libraries.

-- Configuring incomplete, errors occurred!
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj
Microsoft (R) Build Engine version 16.9.0+5e4b48a27 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: INSTALL.vcxproj
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:23 (project):
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "C:/Users/abc/Downloads/sql-1.11.0.0/sql-odbc/build/odbc/cmake/CMakeFiles/CMakeOutput.log".
CMake Error:
  Generator

    NMake Makefiles

  does not support platform specification, but platform

    x64

  was specified.

Copy-Item : Cannot find path 'C:\Users\abc\Downloads\sql-1.11.0.0\sql-odbc\build\aws-sdk\build\bin\Release'
because it does not exist.
At C:\Users\abc\Downloads\sql-1.11.0.0\sql-odbc\scripts\build_windows.ps1:41 char:1
+ Copy-Item $SDK_BUILD_DIR\bin\$CONFIGURATION\* $DRIVER_BIN_DIR
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\abc...ild\bin\Release:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : Cannot find path 'C:\Users\abc\Downloads\sql-1.11.0.0\sql-odbc\build\odbc\cmake\bin\Release'
because it does not exist.
At C:\Users\abc\Downloads\sql-1.11.0.0\sql-odbc\scripts\build_windows.ps1:42 char:1
+ Copy-Item $DRIVER_BUILD_DIR\bin\$CONFIGURATION\* $DRIVER_BIN_DIR
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\abc...ake\bin\Release:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand_

Request to correct/update me if I am missing any more steps here.

**Comment by chloe-zh** [comment]
Thanks for reporting this issue, will investigate

**Comment by CuriousQA** [comment]
Thank you @chloe-zh

**Comment by chloe-zh** [comment]
Hi @CuriousQA , a quick question, to my understanding your request is actually to get the odbc 1.11 windows installer, is that correct? Actually we have the installers available for download directly, you can also build it from source but you don't have to. Here are the links for x64 and x86 installers:
32 bit: https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-clients/opendistro-sql-odbc/windows/Open+Distro+for+Elasticsearch+SQL+ODBC+Driver+32-bit-1.11.0.0-Windows.msi
64 bit: https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-clients/opendistro-sql-odbc/windows/Open+Distro+for+Elasticsearch+SQL+ODBC+Driver+64-bit-1.11.0.0-Windows.msi

But if you do want to build from source, we will take some more time to investigate the cause and workaround, thanks! :)

**Comment by CuriousQA** [comment]
Thanks @chloe-zh  for sharing the link to download the installers. This is what I was actually looking for. Somehow, I was unaware of any links to download the older versions. I'll close the issue.
