### ISSUE TITLE
HAVING clause is throwing "Invalid SQL Query Exception" when there's an aggregate function

### ISSUE THREAD

**Issue by Nitinrajyadav** [opendistro-for-elasticsearch/sql#120]
for example 
`SELECT
  productName,
  productCode
FROM
  productsindex
WHERE
  (productName = 'test')
GROUP BY
  productCode
HAVING
  COUNT(calculatedQATS) < 20
`

throws exception  see **HAVING COUNT(calculatedQATS) < 20**

but 

`SELECT
  productName,
  productCode
FROM
  productsindex
WHERE
  (productName = 'test')
GROUP BY
  productCode
HAVING
 calculatedQATS < 20
`

Works  see **HAVING calculatedQATS < 20**

also, this's a random query copied from w3school (replaced table-name with valid index-name)
`SELECT COUNT(CustomerID), Country FROM productsindex GROUP BY Country HAVING COUNT(CustomerID) > 5` 
this also throws **invalid query exception**

**Comment by dai-chen** [comment]
Thanks for reporting the issue! We don't have support for your cases:

 + I assume you're trying to use `HAVING` on fields that have nothing to do with fields in `SELECT`.
 + Alias for aggregate expressions present in `HAVING` is required in our plugin. Please try query like this: `SELECT COUNT(CustomerID) AS cnt, Country FROM productsindex GROUP BY Country HAVING cnt > 5`

You can check out example in our README or test cases: https://github.com/opendistro-for-elasticsearch/sql#sql-usage

And also I've only seen same aggregate expression(s) present in `HAVING` and `SELECT`. I'm wondering is query in your first 2 examples valid in standard SQL?

**Comment by Nitinrajyadav** [comment]
@dai-chen thanks for the clarification. 

> and to answer your question, I believe the first query in my question is to be valid in standard SQL syntax you can check here https://www.eversql.com/sql-syntax-check-validator/ I've tested that in Sequel-PRO.

> and the second Query, I was playing with the **/_explain** API endpoint, and it was excepted as valid SQL syntax, however, in Standard SQL, it's not valid, it should have **calculatedQATS** in SELECT statement as a column or alias.

**Comment by dai-chen** [comment]
> @dai-chen thanks for the clarification.
> 
> > and to answer your question, I believe the first query in my question is to be valid in standard SQL syntax you can check here https://www.eversql.com/sql-syntax-check-validator/ I've tested that in Sequel-PRO.
> 
> > and the second Query, I was playing with the **/_explain** API endpoint, and it was excepted as valid SQL syntax, however, in Standard SQL, it's not valid, it should have **calculatedQATS** in SELECT statement as a column or alias.

Thanks for the information! Yeah, I realized that the first query is valid and found example in some RDBMS. Will tag this issue as "Enhancement" for tracking. For now, you can play with query in the syntax I posted which is expected to work. Thanks!
