### ISSUE TITLE
Dot/period at start of index name fails to parse

### ISSUE THREAD

**Issue by aetter** [opendistro-for-elasticsearch/sql#121]
```json
POST _opendistro/_sql
{
  "query": "SELECT * FROM .kibana LIMIT 50"
}
```

This query fails with the following error:

```json
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "ERROR. token : DOT, pos : 15",
    "type": "ParserException"
  },
  "status": 400
}
```

Indices starting with `.` is perfectly valid in Elasticsearch, so unless there's a good reason, I think we should support this operation.

**Comment by abbashus** [comment]
Thanks @aetter , looks like a valid case. Even wrapping `.kibana` in back-ticks and single quotes is not working. We will look into it and come with a fix.

**Comment by dai-chen** [comment]
> Thanks @aetter , looks like a valid case. Even wrapping `.kibana` in back-ticks and single quotes is not working. We will look into it and come with a fix.

I remember we ran into the similar issue for identifiers in back-ticks when evaluating support for Tableau. @qreshi may have more context.

**Comment by dai-chen** [comment]
New issue related: https://github.com/opendistro-for-elasticsearch/sql/issues/212
