### ISSUE TITLE
Error when the order by is by function that is not included into select list for aggregation query

### ISSUE THREAD

**Issue by galkk** [opendistro-for-elasticsearch/sql#123]
The following query throws an exception
```
GET _opendistro/_sql 
{
  "query" : "SELECT ip, count(*) from kibana_sample_data_logs group by ip order by sum(bytes) desc "
}
```

```
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "No mapping found for [SUM(bytes)] in order to sort on",
        "index_uuid": "CnrZKkl9QAycNU34PXa04Q",
        "index": "kibana_sample_data_logs"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "kibana_sample_data_logs",
        "node": "MxFp78opRk6Vuc5JK7bzFw",
        "reason": {
          "type": "query_shard_exception",
          "reason": "No mapping found for [SUM(bytes)] in order to sort on",
          "index_uuid": "CnrZKkl9QAycNU34PXa04Q",
          "index": "kibana_sample_data_logs"
        }
      }
    ]
  },
  "status": 400
}
```

Related to [issue #75](https://github.com/opendistro-for-elasticsearch/sql/issues/75)

**Comment by Nitinrajyadav** [comment]
I'm also having the somewhat similar issue
>`"query": "SELECT * FROM productsindex ORDER BY  lower(brand_brandName)  ASC" `
                **"reason": "No mapping found for [lower(brand_brandName)] in order to sort on",**

>one of the workarounds in my case would be to use  `COLLATE NOCASE`, but COLLATE is not supported yet. 
Do you guys have any plans for supporting COLLATE?

**Comment by galkk** [comment]
Thanks for feedback Nitin. As of now there is no support for case change functions, but I created issue to track that request: [#128](https://github.com/opendistro-for-elasticsearch/sql/issues/128)

**Comment by Nitinrajyadav** [comment]
@galkk thanks for the quick response. 
You guys are doing amazing work here 👍

**Comment by dai-chen** [comment]
In https://github.com/opendistro-for-elasticsearch/sql/issues/250, I found even the aggregate function is included in `SELECT`, the DSL is wrong too. We seem only support using field alias of aggregate function in `ORDER BY`.

**Comment by dai-chen** [comment]
The issue has been fixed in new query engine (which is for now experimental and disabled by default). You can enable it to preview by changing the plugin setting: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled. Thanks!
