### ISSUE TITLE
Move the index mapping definitions to standalone json files

### ISSUE THREAD

**Issue by arsen-es** [opendistro-for-elasticsearch/sql#138]
All mappings are currently defined in `src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/TestUtils.java` as java strings, which makes it difficult to find/maintain/properly indent when updating/verify validity of json. We need to create one small json per index mapping and load it at run-time.

**Comment by pakio** [comment]
@arsen-es Hi! I tried to fix this issue. if you haven't picked up yet, i'd be grateful if you would check my PR https://github.com/opendistro-for-elasticsearch/sql/pull/526

**Comment by anirudha** [comment]
We Will prioritize it next week , thanks!

**Comment by dai-chen** [comment]
@pakio Thanks for your fix! Resolving the issue.
