### ISSUE TITLE
SQL Command Line Interface to access OpenDistro ES

### ISSUE THREAD

**Issue by abbashus** [opendistro-for-elasticsearch/sql#140]
We want to create a Elasticsearch SQL CLI so users can interact with Elasticsearch with familiar SQL syntax from the comfort of their terminals. Users can run any SQL queries that OpenDistro SQL plugin supports and get results without going through Kibana. This CLI is going should be a cross-platform stand alone application and can simply be installed via package manager.

Some good to have features(in no particular order):

- Multi-line input
- Auto-completion (SQL keyword suggestion, index name suggestion)
- Table like formatted output
- Syntax Highlighting
- History for the last N queries
- Configuration to tweak CLI behavior.
- Run ad-hoc SQL query directly without going through CLI console.

**Comment by dai-chen** [comment]
The project is in progress and will have separate repository for its own issue tracking.
