### ISSUE TITLE
CSV and JDBC export are 2 different execution paths

### ISSUE THREAD

**Issue by galkk** [opendistro-for-elasticsearch/sql#148]
CSV and JDBC result formatting have 2 parallel codebases, so fix in one wouldn't work with another and one needs to always remember to double check. Example: CSV formatter supported all aggregations (Percentile, Numeric SimpleValue, Numeric Multiple), and JDBC supported only one: Numeric SimpleValue

Recommendation: the CSV formatter should use results of JDBC formatter and do simple transformation of results. The logic, that is currently not presented in JDBC formatter must be brought there

CSV formatting: CSVResultsExtractor.java
JDBC/RAW: SelectResultSet.java

**Comment by abbashus** [comment]
+1.

**Comment by dai-chen** [comment]
This has been resolved in new query engine.
