### ISSUE TITLE
Fix script functions: remove hardcoded parameters

### ISSUE THREAD

**Issue by galkk** [opendistro-for-elasticsearch/sql#150]
This is followup for #149, with the same rationale

The following SQL
```sql
GET /_opendistro/_sql/_explain
{
  "query": """
    SELECT name, substring(name, 0, 3) 
    FROM employess_with_missing
    WHERE substring(name, 0, 3) = 'bob'
  """
}
```

produces the following DSL

```json
{
  "from": 0,
  "size": 200,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "script": {
                  "script": {
                    "source": "def substring_1707568387 = doc['name'].value.substring(0, 3);substring_1707568387 == 'bob'",
                    "lang": "painless"
                  },
                  "boost": 1
                }
              }
            ],
            "adjust_pure_negative": true,
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "_source": {
    "includes": [
      "name"
    ],
    "excludes": []
  },
  "script_fields": {
    "substring_1954371849": {
      "script": {
        "source": "def substring_427843559 = doc['name'].value.substring(0, 3);return substring_427843559;",
        "lang": "painless"
      },
      "ignore_failure": false
    }
  }
}
```

As per Elastic doc https://www.elastic.co/guide/en/elasticsearch/reference/7.3/modules-scripting-using.html#prefer-params

the script should use parameters, not hardcoded fields

Basically, in generated DSL instead of this
```json
                "script": {
                  "script": {
                    "source": "def substring_1707568387 = doc['name'].value.substring(0, 3);substring_1707568387 == 'bob'",
                    "lang": "painless",
```

we should have 

```json
                  "script": {
                    "source": " doc[params.p0].value.substring(params.p1, params.p2) == params.p3",
                    "lang": "painless",
                    "params": {
                      "p0" : "name",
                      "p1": 0,
                      "p2": 3,
                      "p3": "bob"
                    }
                  },
```

for substring and any other function.

**Comment by galkk** [comment]
Otherwise, theoretically, there could be even kind of DDOS attack, because Elastic limits amount of inline scripts precompiled

> If you compile too many unique scripts within a small amount of time, Elasticsearch will reject the new dynamic scripts with a circuit_breaking_exception error. By default, up to 15 inline scripts per minute will be compiled. You can change this setting dynamically by setting script.max_compilations_rate.

**Comment by donggong** [comment]
script.max_compilations_rate 这个值放开会对es集群有什么影响呢？

**Comment by dai-chen** [comment]
> script.max_compilations_rate 这个值放开会对es集群有什么影响呢？

Hi @donggong,

https://www.elastic.co/guide/en/elasticsearch/reference/7.4/circuit-breaker.html: "Limit for the number of unique dynamic scripts within a certain interval that are allowed to be compiled. Defaults to 75/5m, meaning 75 every 5 minutes."

这个配置是用来限制一定时间内，ES编译script的数量。例如你的每个DSL请求里都包含很多不一样的painless脚本的话，ES会做限制。因为我理解编译script应该比较耗费CPU资源，所以如果你将这个配置改成很大的话，可能会导致ES占用很多CPU。一种改进方法就像这个issue里提到的，将script中变化的部分提取成入參，类似于SQL里的PreparedStatement。
