### ISSUE TITLE
Migrate Legacy Integration Tests to ESTest in Gradle

### ISSUE THREAD

**Issue by dai-chen** [opendistro-for-elasticsearch/sql#17]
There are still quite a few integration tests in Maven which perform "fake" integration testing (create core classes of plugin in memory with connection to an external ES cluster). We need to migrate all of them to Gradle to do it in standard ES Test manner.

**Comment by arsen-es** [comment]
All test classes are now migrated, there are some test cases which are blocked by different reasons, but those will be tracked in their own issues, resolving this.
