### ISSUE TITLE
Support for track_total_hits in _sql

### ISSUE THREAD

**Issue by tyd** [opendistro-for-elasticsearch/sql#196]
We're able to use track_total_hits:true using the Query DSL and get total hits as expected, but when using __opendistro/_sql_, this option doesn't seem to be supported and it maxes out with the _gte 10,000_. I've included some examples below. 

Is there another way to get the total hits with __opendistro/_sql_ without doing a second query with count(*)? If not, can this functionality be added?

#### Request
```
GET test_data/_search
{
    "track_total_hits": true,
    "query": {
        "match_all": { }
    }
}
```

#### Response
```
...
  "hits" : {
    "total" : {
      value" : 1160564
      "relation" : "eq"
    },
...
```

#### Request
```
POST _opendistro/_sql
{
  "track_total_hits": true,
  "query": "SELECT * FROM test_data"
}
```

#### Response
```
...
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
...
```

#### Expected output
```
...
  "hits" : {
    "total" : {
      "value" : 1160564,
      "relation" : "eq"
    },
...
```

**Comment by dai-chen** [comment]
Thanks for reporting! If I recall right, we only parse the field out of the request body so I assume your `"track_total_hits": true` would be ignored. Will investigate further and update here.

**Comment by penghuo** [comment]
@tyd Could you help me understand your use case when you said `Is there another way to get the total hits with __opendistro/sql without doing a second query with count(*)?`. Do you mean to get the matched value and total count in the same response?

**Comment by tyd** [comment]
@penghuo I was just asking if there is another, perhaps undocumented way, to get the total hits returned with a single call such as when `"track_total_hits": true` is used with the Query DSL in my example above..

**Comment by penghuo** [comment]
@tyd , currently opendisto-sql doesn't support fetch the total hits in one query. I am asking to understand your used why you want to get the total hits value in the same value. In my understanding, the total count usually used in aggregation case.
If this use cases is important to customer, we will consinder prioritize it.

**Comment by tyd** [comment]
@penghuo we're looking to migrate to AWS ElasticSearch and would like to utilize the SQL functionality to power various parts of our application. Part of this migration would be a requirement to show total hits to our users (for data grids, search result summaries, paging etc). 

We'd like to accomplish this in the most efficient way and avoid having to do 2 queries. The query DSL supports `"track_total_hits": true` to do this in a single query and I was hoping this support could be added to `__opendistro/sql` to do the same.

**Comment by penghuo** [comment]
@tyd Thanks for the explaination. Since we are more focus on the support of ordinary SQL feature on top of elasticsearch, currently we don't have plan to support this.
By the way, I think you can use the _opendistro/_sql/_explain to translate the SQL to Elasticsearch DSL. Then you can include track_total_hits in the DSL and execute the DSL against the Elasticsearch ( (assuming there is no JOIN).
