### ISSUE TITLE
SQL Plugin from Dev Tools not working

### ISSUE THREAD

**Issue by ryanpagel** [opendistro-for-elasticsearch/sql#198]
I'm not getting back any results using the SQL plugin in Dev Tools.  SQL queries work using REST calls directly (using Postman for example).  I'm using OpenDistro 1.2.0.  I haven't made any modifications to the installation.  I've tested this on two different installations of OpenDistro.

**To reproduce**, perform the following from Kibana Dev Tools:

Create a new index and add a document to it.
`PUT test/_doc/1
{
  "test": "testing"
}`

Then issue a SQL query on that index in Dev Tools:
`GET _sql
{
  "query": "select * from test"
}`

It returns the following result:
`{
  "error": "Incorrect HTTP method for uri [/_sql?pretty] and method [POST], allowed: [DELETE, HEAD, PUT, GET]",
  "status": 405
}`

**Comment by ryanpagel** [comment]
Actually I solved my own problem... needed to use `_opendistro/_sql` instead of just `_sql`.

**Comment by dai-chen** [comment]
> Actually I solved my own problem... needed to use `_opendistro/_sql` instead of just `_sql`.

Yeah, glad you figured out :). Please refer to our READMD and technical documentation for more details: https://opendistro.github.io/for-elasticsearch-docs/docs/sql/
