### ISSUE TITLE
Support ordinal in GROUP/ORDER BY clause

### ISSUE THREAD

**Issue by dai-chen** [opendistro-for-elasticsearch/sql#215]
In issue https://github.com/opendistro-for-elasticsearch/sql/issues/213, it seems BI tool like Tableau will generates `GROUP BY` (and probably `ORDER BY` too) using ordinal.

Take query `SELECT age FROM accounts GROUP BY 1` for example, the ordinal 1 here is referring to field `age`. So actually this query is Equivalent to ` SELECT age FROM accounts GROUP BY age`. Although it's said this is not a good practice, we need to support this for integration with BI tool.

Reference: 
1. https://stackoverflow.com/questions/7392730/what-does-sql-clause-group-by-1-mean
2. https://dba.stackexchange.com/questions/86609/why-do-we-use-group-by-1-and-group-by-1-2-3-in-sql-query

**Comment by abbashus** [comment]
Fixed by #248.
