### ISSUE TITLE
Support for extra functions required by BI tools 

### ISSUE THREAD

**Issue by rupal-bq** [opendistro-for-elasticsearch/sql#224]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
Dataset: Flights sample data (loaded through Kibana)
SQL Plugin version: 1.1.0.1
Tableau version: 2019.3

Tableau generated SQL (MySQL dialect):  ```SELECT POWER(`kibana_sample_data_flights`.`dayOfWeek`, 2) AS `sum_Calculation_160722252357632000_ok`\nFROM `kibana_sample_data_flights`\nGROUP BY 1.1000000000000001```

Generated SQL without quotes (#212) and Group By (#215): `SELECT power(dayOfWeek, 2) AS sum_Calculation_160722252357632000_ok FROM kibana_sample_data_flights`

Result: No data
```
{[\n]"
  "error": {[\n]"
    "reason": "There was internal problem at backend",[\n]"
    "details": "The following method is not supported in Schema: power",[\n]"
    "type": "UnsupportedOperationException"[\n]"
  },[\n]"
  "status": 500[\n]"
}
```

Expected Behaviour: Should return square of all values present in column dayOfWeek.

List of functions which have similar issue:
Number functions

- ATAN2
- COT 
- SIGN 
- POWER

String functions

- ASCII
- RTRIM
- LTRIM
- LOCATE
- LENGTH
- REPLACE
- LEFT
- RIGHT

Logical functions

- IFNULL
- ISNULL

**Comment by dai-chen** [comment]
I think this is the limitation in our JDBC formatter. Currently the formatter doesn't recognize many SQL function and map it to correct result type in JDBC spec.

**Comment by dai-chen** [comment]
For these functions, first we need to change grammar to pass both new and old SQL parser. Then based on their behaviors in standard SQL or MySQL, we need to figure out what's the right DSL to generate.

**Comment by dai-chen** [comment]
Another function list that we need to support: https://github.com/opendistro-for-elasticsearch/sql/issues/235.

**Comment by chloe-zh** [comment]
@dai-chen I will do #235  along with this issue.

**Comment by chloe-zh** [comment]
PRs will be separated and submitted respectfully according to the function/operator type.
