### ISSUE TITLE
Support for CAST() function

### ISSUE THREAD

**Issue by rupal-bq** [opendistro-for-elasticsearch/sql#225]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
Dataset: Flights sample data (loaded through Kibana)
SQL Plugin version: 1.1.0.1

Query: ```SELECT cast(dayOfWeek AS FLOAT) AS calculation FROM kibana_sample_data_flights```

Result: No data
```
{[\n]"
  "error": {[\n]"
    "reason": "Invalid SQL query",[\n]"
    "details": "Failed to parse query due to offending symbol [AS] at: 'SELECT cast(dayOfWeek AS' <--- HERE... More details: Expecting tokens in {'SELECT', '('}",[\n]"
    "type": "SyntaxAnalysisException"[\n]"
  },[\n]"
  "status": 400[\n]"
}
```

Expected Behaviour: Should return all values from column `dayOfWeek` as float.

**Comment by dai-chen** [comment]
We removed `CAST` syntax in new parser grammar because we thought we don't support it. Actually there are UTs in codebase however UT won't run with new parser. Need to add it back.

**Comment by dai-chen** [comment]
Apart from the changes in grammar, need to add ITs to cover this case.

**Comment by dai-chen** [comment]
CAST syntax removed accidentally: https://github.com/antlr/grammars-v4/blob/master/mysql/Positive-Technologies/MySqlParser.g4#L2133
