### ISSUE TITLE
Unable to process nested aggregate functions

### ISSUE THREAD

**Issue by jordanw-bq** [opendistro-for-elasticsearch/sql#229]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
**Dataset:** Flights sample data (loaded through Kibana)
**SQL Plugin version:** 1.1.0.1

**Example Query:**
SELECT TAN(MAX(AvgTicketPrice)) FROM kibana_sample_data_flights

**Results:**
Raw response received: {
  "error": {
    "reason": "Invalid SQL query",
    "details": "",
    "type": "NullPointerException"
  },
  "status": 400
}

**Expectation:**
No error, and outer function should be correctly applied to the aggregation result.
Example: (run with MySQL using subset of Flights data, so calculation result is not exact)
```
| TAN(MAX(AvgTicketPrice)) | 
| 0.3662764123396319 |
```

**Comment by dai-chen** [comment]
Just checked `SELECTMAX(AvgTicketPrice) ...` can work individual for query without `GROUP BY`. But function composition breaks both execution and explain and ends up throwing NPE.

**Comment by penghuo** [comment]
closed with commit.https://github.com/opendistro-for-elasticsearch/sql/commit/3730ac6e9b3a363c51432b34d2104567eb9babb7
