### ISSUE TITLE
LOG() function causes the client to hang

### ISSUE THREAD

**Issue by rupal-bq** [opendistro-for-elasticsearch/sql#231]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
Dataset: Flights sample data (loaded through Kibana)
SQL Plugin version: 1.1.0.1
Tableau version: 2019.3
 
Query: ```SELECT log(FlightDelayMin) AS sum_Calculation_160722252357632000_ok FROM kibana_sample_data_flights```

Result: Client hangs and server return following error.
```
odfe-node1    | [2019-10-18T17:14:50,425][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [odfe-node1] uncaught exception in thread [elasticsearch[odfe-node1][sql-worker][T#9]]
odfe-node1    | java.lang.IllegalStateException: Request id not present in current context
odfe-node1    |     at com.amazon.opendistroforelasticsearch.sql.utils.LogUtils.getRequestId(LogUtils.java:54) ~[?:?]
odfe-node1    |     at com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.lambda$async$1(AsyncRestExecutor.java:134) ~[?:?]
odfe-node1    |     at com.amazon.opendistroforelasticsearch.sql.utils.LogUtils.lambda$withCurrentContext$0(LogUtils.java:72) ~[?:?]
odfe-node1    |     at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.1.1.jar:7.1.1]
odfe-node1    |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
odfe-node1    |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
odfe-node1    |     at java.lang.Thread.run(Thread.java:834) [?:?]
```

Expected Behaviour: Should return log of all the values in column `FlightDelayMin`.

**Comment by dai-chen** [comment]
`LOG` works. This exception is caused by that request ID in our log context is not set properly. Not sure if we have this issue in multi-thread setup. Need to look into the code. I guess you should be good if you rerun your query.

**Comment by rupal-bq** [comment]
This is a consistent issue for us.

**Comment by dai-chen** [comment]
Didn't reproduce from my side and this is only for old engine.
