### ISSUE TITLE
Add support for JOINs without aliases

### ISSUE THREAD

**Issue by jordanw-bq** [opendistro-for-elasticsearch/sql#232]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
**Dataset:** Flights & Ecommerce sample data (loaded through Kibana)
**SQL Plugin version:** 1.1.0.1

**Example Query:**
SELECT AvgTicketPrice AS AvgTicketPrice,   Cancelled AS Cancelled,   Carrier AS Carrier,   DestAirportID AS DestAirportID,   DestCityName AS DestCityName,   DestCountry AS DestCountry,   DestLocation AS DestLocation FROM kibana_sample_data_ecommerce   LEFT JOIN kibana_sample_data_flights ON (kibana_sample_data_ecommerce.day_of_week_i = dayOfWeek) LIMIT 50

**Results:**
No data
```
{
  "schema": [],
  "total": 10000,
  "datarows": [
    [],
    [],
    [],
    [],
...
    []
  ],
  "size": 50,
  "status": 200
}
```

**Notes:**
This is a known limitation of JOINs with Elasticsearch, but Tableau by default will be generating JOINs without aliases.

**Expectation:**
Support for JOINs without alias

**Comment by dai-chen** [comment]
Currently alias is required for `JOIN`.
