### ISSUE TITLE
Function names are case-sensitive

### ISSUE THREAD

**Issue by jordanw-bq** [opendistro-for-elasticsearch/sql#233]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
**Dataset:** Flights sample data (loaded through Kibana)
**SQL Plugin version:** 1.1.0.1

**Example Query:**
SELECT SUBSTRING(OriginWeather, 1, 2)  FROM kibana_sample_data_flights

**Result:**
```
Internal Server Error. Reason: There was internal problem at backend. Type: UnsupportedOperationException. Details: The following method is not supported in Schema: SUBSTRING
	at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.executeQueryRequest(StatementImpl.java:78)
	at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.executeQueryX(StatementImpl.java:61)
	at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.execute(StatementImpl.java:170)
```

**Note:**
`SELECT substring(OriginWeather, 1, 2)...` returns results as intended.

**Expectation:**
Tableau will use UPPERCASE function names in almost all cases. Casing should not matter for function names in a query.

**Comment by dai-chen** [comment]
Actually both our old and new parser are case-insensitive to function name. This issue is similar as https://github.com/opendistro-for-elasticsearch/sql/issues/224 and thrown from our JDBC formatter.

**Comment by dai-chen** [comment]
Just checked our formatter seems match function name in case sensitive way (simply look it up in hash set).

**Comment by galkk** [comment]
related to #176
