### ISSUE TITLE
Arithmetic operations not supported in WHERE clause

### ISSUE THREAD

**Issue by jordanw-bq** [opendistro-for-elasticsearch/sql#234]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
**Dataset:** Flights sample data (loaded through Kibana)
**SQL Plugin version:** 1.1.0.1

**Example Query:**
SELECT FlightNum FROM kibana_sample_data_flights where (AvgTicketPrice + 100) <= 1000

**Result:**
```
Raw response received: {
  "error": {
    "reason": "Invalid SQL query",
    "details": "No enum constant com.amazon.opendistroforelasticsearch.sql.domain.Where.CONN.<=",
    "type": "IllegalArgumentException"
  },
  "status": 400
}
```

**Expected Behaviour:**
No error, and the operation should be applied to the field before the comparison is made.
Example results:
```
| FlightNum | 
| 9HY9SWR | 
| X98CCZO | 
| UFK2WIZ | 
| EAYQW69 | 
| 58U013N | 
| XEJ78I2 | 
| EVARI8I | 
...
```

**Comment by dai-chen** [comment]
Similar as this one: https://github.com/opendistro-for-elasticsearch/sql/issues/194. Currently we don't support arithmetic expression anywhere in query.

**Comment by dai-chen** [comment]
This is already fixed in new query engine. However, the new engine is disabled by default for now. You can enable it by following the instruction here: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled
