### ISSUE TITLE
Unable to recognize certain function names

### ISSUE THREAD

**Issue by rupal-bq** [opendistro-for-elasticsearch/sql#235]
Using Docker image amazon/opendistro-for-elasticsearch:1.1.0
Dataset: Flights sample data (loaded through Kibana)
SQL Plugin version: 1.1.0.1
Tableau version: 2019.3

Query:  `SELECT month(timestamp) AS mn_timestamp_ok FROM kibana_sample_data_flights`

Result: No data
```
{[\n]"
  "error": {[\n]"
    "reason": "Invalid SQL query",[\n]"
    "details": "Function [MONTH] cannot be found or used here. Did you mean [DAY_OF_MONTH]?",[\n]"
    "type": "SemanticAnalysisException"[\n]"
  },[\n]"
  "status": 400[\n]"
}
```
Expected Behaviour: Should return respective month for the values in column `timestamp`

List of functions which have similar issue:

Date Functions
- MONTH
- DAYOFMONTH
- DATE
- MONTHNAME
- TIMESTAMP
- MAKETIME
- NOW
- CURDATE

Logical Function
- IF

**Comment by dai-chen** [comment]
Checked the code that these functions are missing or have different name. Here are the list of data functions we support for now:

```
            "date_format", "year", "month_of_year", "week_of_year", "day_of_year", "day_of_month",
            "day_of_week", "hour_of_day", "minute_of_day", "minute_of_hour", "second_of_minute"
```
