### ISSUE TITLE
Boolean expressions not supported in SELECT clause

### ISSUE THREAD

**Issue by jordanw-bq** [opendistro-for-elasticsearch/sql#237]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
**Dataset:** Flights sample data (loaded through Kibana)
**SQL Plugin version:** 1.1.0.1

**Example Query:**
SELECT ((Origin = 'Frankfurt am Main Airport') and (Dest = 'Sydney Kingsford Smith International Airport')) AS Calculation_462181953506873347 FROM kibana_sample_data_flights 

**Results:**
```
Raw response received: {
  "error": {
    "reason": "Invalid SQL query",
    "details": "AND is not support",
    "type": "SqlParseException"
  },
  "status": 400
}
```

**Expectation:**
Should return a boolean value for the result of the expression.
Example results: (query run with MySQL on small subset of Flights data)
```
| Calculation_462181953506873347 | 
| 1 | 
| 0 | 
| 0 | 
| 0 | 
| 0 | 
| 0 |
...
```

**Comment by chloe-zh** [comment]
Related issue: #256

**Comment by dai-chen** [comment]
This is already fixed in new query engine. However, the new engine is disabled by default for now. You can enable it by following the instruction here: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled
