### ISSUE TITLE
Add support for CASE statement

### ISSUE THREAD

**Issue by rupal-bq** [opendistro-for-elasticsearch/sql#239]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
Dataset: Flights sample data (loaded through Kibana)
SQL Plugin version: 1.1.0.1
Tableau version: 2019.3

Query: `` SELECT (case OriginWeather when 'Sunny' then '1' when 'Rain' then '0' else 'NA' end) AS Calculation_462181953506873347 FROM kibana_sample_data_flights``

Result: No data
```
{[\n]"
    "error": {[\n]"
    "reason": "Invalid SQL query",[\n]"
    "details": "err find condition class com.alibaba.druid.sql.ast.expr.SQLCharExpr",[\n]"
    "type": "SqlParseException"[\n]"
  },[\n]"
  "status": 400[\n]"
}
```

Expected Behaviour: Should return `1` for `Sunny`, `0` for `Rain` and `NA` for all other values in column `OriginWeather`

**Comment by jordanw-bq** [comment]
Different behaviour in CASE with NOT(). This might be related, or it could be a separate issue with the NOT() function.

Query:
`SELECT (case when (AvgTicketPrice > 500) THEN 'High' when not (AvgTicketPrice > 500) then 'Low' else null end) AS Calculation_462181953506873347 FROM kibana_sample_data_flights`

Result:
```
Type: ClassCastException. Details: class com.amazon.opendistroforelasticsearch.sql.domain.MethodField cannot be cast to class com.amazon.opendistroforelasticsearch.sql.domain.ScriptMethodField (com.amazon.opendistroforelasticsearch.sql.domain.MethodField and com.amazon.opendistroforelasticsearch.sql.domain.ScriptMethodField are in unnamed module of loader java.net.FactoryURLClassLoader @3330f3ad)
```

**Comment by dai-chen** [comment]
I can find 1 test case in codebase for `CASE` with a little different syntax: `SELECT address, CASE WHEN gender='0' THEN 'aaa' ELSE 'bbb' END AS a2345, count(age)`. Maybe we only support case statement written in this manner.

**Comment by dai-chen** [comment]
`CASE` statement does have 2 forms: https://dev.mysql.com/doc/refman/5.7/en/case.html.
