### ISSUE TITLE
Remove default size limit(200)

### ISSUE THREAD

**Issue by Jianfei-Li** [opendistro-for-elasticsearch/sql#244]
The plugin is adding a default response size of 200 [here](https://github.com/opendistro-for-elasticsearch/sql/blob/master/src/main/java/com/amazon/opendistroforelasticsearch/sql/domain/Select.java#L53).

Below are the requirements:

1. The plugin should return all the matches records if there is no size limit in the SQL request.  The response probably should be paginated. 
2. If there is a size limitation in the SQL request, response should be based on the limitation number, even if the limitation number is larger than 10000. The response probably should be paginated. 
3. This should also work for group by SQLs.

**Comment by dai-chen** [comment]
Thanks for reporting! Will evaluate the efforts needed.

Issue related: https://github.com/opendistro-for-elasticsearch/sql/issues/16

**Comment by dai-chen** [comment]
@Jianfei-Li Abbas has merged his PR https://github.com/opendistro-for-elasticsearch/sql/pull/390 for simple query (no GROUP BY and JOIN) pagination support. Please see design doc https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/dev/Pagination.md for more details. Changes for JDBC driver will be merged later.
