### ISSUE TITLE
Case-sensitivity affects query results

### ISSUE THREAD

**Issue by arsen-es** [opendistro-for-elasticsearch/sql#25]
Let's say we have an index **people** of **person** documents like this one:
```json
{
  "name" : {
    "first" : "Jane",
    "last" : "Doe"
  }
}
```
and another index **people2** of similar documents.

Now if there are people with names "Jane" and "John" in both indices, then intuitively executing the following query you expect to get those 2 results back, but you get no hits:

```sql
SELECT * FROM people/person WHERE name.first IN (SELECT name.first FROM people2/person);
```

However, if the index uses a standard mapping (with standard tokenizer/analyzer), then all the terms will be lower-cased. Basically the nested `SELECT` query will return the names in original casing (starting with a capital letter), but the main `SELECT` will fail to find any matches, because it will search within lowercase terms.

Seems like this is by design, but also contradicts the SQL logic and intuition.

**Comment by arsen-es** [comment]
Just to make it simpler, even this query would return no hits:
```sql
SELECT * FROM people/person WHERE name.first='Jane';
```

**Comment by abbashus** [comment]
What are the underlying mappings used here for **person** type?

**Comment by arsen-es** [comment]
```json
"mappings": {
  "person" : {
    "properties": {
      "name": {
        "properties": {
          "first": {
            "type": "text",
            "fielddata": true
          },
          ...
        }
      }
    }
  }
}
```

**Comment by jngz-es** [comment]
Currently the outcome of only 'text' type field in where condition is not defined.

**Comment by abbashus** [comment]
For `where` like SQL behavior with equal operator  `where name.first = 'Jane'`, the mapping should be changed to use type keyword

```
"mappings": {
  "person" : {
    "properties": {
      "name": {
        "properties": {
          "first": {
            "type": "text",
           "fields": {
            "keyword": { 
              "type": "keyword"
            }
          },
          ...
        }
      }
    }
  }
}
```

**Comment by arsen-es** [comment]
Alright, based on offline conversations with the team, resolving this as not an issue, the behavior matches the term query behavior, and it is by design.
