### ISSUE TITLE
Support Escape Sequences 

### ISSUE THREAD

**Issue by rupal-bq** [opendistro-for-elasticsearch/sql#252]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
Dataset: Flights sample data (loaded through Kibana)
SQL Plugin version: 1.1.0.2
Tableau version: 2019.3

Tableau generated SQL (MySQL dialect): ``` SELECT YEAR(`kibana_sample_data_flights`.`timestamp`) AS `yr_timestamp_ok`\nFROM `kibana_sample_data_flights`\nGROUP BY 1 ```

Result: No data
```
{[\n]"
  "error": {[\n]"
    "reason": "Invalid SQL query",[\n]"
    "details": "Failed to parse query due to offending symbol [\\n] at: 'SELECT YEAR(`kibana_sample_data_flights`.`timestamp`) AS `yr_timestamp_ok`\\n' <--- HERE... More details: Expecting tokens in {'SELECT', '('}",[\n]"
    "type": "SyntaxAnalysisException"[\n]"
  },[\n]"
  "status": 400[\n]"
}"
```

Expected Behaviour: Should return year of all values present in column `timestamp`.

**Comment by penghuo** [comment]
## Test with MySQL 5.6, get the similar error.

### Test Env
http://sqlfiddle.com/#!9/7f8a75/8

### SQL
```
SELECT name \nFROM MovieStar A
```
### Response
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\nFROM MovieStar A' at line 1
```

**Comment by rupal-bq** [comment]
Tableau is adding `\n` in logs but it doesn't seem to be a part of executed queries.
