### ISSUE TITLE
Support literal types other than number literal in SELECT clause

### ISSUE THREAD

**Issue by chloe-zh** [opendistro-for-elasticsearch/sql#256]
We have supported number literals in SELECT, but the other types including string, datetime etc. are still in vacancy. 

Related issue: **[#254 Support SELECT <literal>](https://github.com/opendistro-for-elasticsearch/sql/issues/254)**

**Comment by dai-chen** [comment]
For now string literal in SELECT will be treated as field name and ends up with unknown field name exception in both new semantic analyzer and backend code:

Run the query with string literal selected:

```
POST _opendistro/_sql?format=jdbc
{
  "query": "SELECT 'abc' FROM `kibana_sample_data_flights`"
}

{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Field ['abc'] cannot be found or used here. Did you mean [Cancelled]?",
    "type": "SemanticAnalysisException"
  },
  "status": 400
}
```

Disable new parser and run again:

```
PUT /_cluster/settings
{
  "transient": {
    "opendistro.sql.query.analysis.enabled": "false"
  }
}

{
  "error": {
    "reason": "Invalid SQL query",
    "details": "unknown field name : 'abc'",
    "type": "SqlParseException"
  },
  "status": 400
}
```

**Comment by dai-chen** [comment]
The basic support for SELECT literal without query (FROM) is already added into new query engine. Docs for introducing the new query engine will be added soon. We're adding support for more expression and clauses in new engine at the moment so resolving this issue for now..
