### ISSUE TITLE
LOG function doesn't work given base

### ISSUE THREAD

**Issue by dai-chen** [opendistro-for-elasticsearch/sql#263]
This seems a bug: https://github.com/opendistro-for-elasticsearch/sql/blob/adddd93a36f8ce908769b64ce8994a90445dbddd/src/main/java/com/amazon/opendistroforelasticsearch/sql/utils/SQLFunctions.java#L289. We always use the first argument of `LOG` and for some reason the test code is also wrong.

And in the link above, there is an array list created for each function call which seems unnecessary. `LOG` is heavily used in BI tool so we need to make sure it is correct and efficient.

Example: you can see in the explain output, the script is always division of 2 same numbers.

```
POST /_opendistro/_sql/_explain
{
  "query": "SELECT LOG(2, 4) AS log FROM accounts"
}

{
  "from" : 0,
  "size" : 200,
  "_source" : {
    "includes" : [ ],
    "excludes" : [ ]
  },
  "script_fields" : {
    "log" : {
      "script" : {
        "source" : "def log_1 = Math.log(4)/Math.log(4);return log_1;",
        "lang" : "painless"
      },
      "ignore_failure" : false
    }
  }
}
```

**Comment by chloe-zh** [comment]
I will do a quick fix to it.

**Comment by chloe-zh** [comment]
I'll also add LN next to it since MySQL supports it.
