### ISSUE TITLE
Multiple GROUP BY size restriction in 2nd to nth aggregation

### ISSUE THREAD

**Issue by subliminalvoice** [opendistro-for-elasticsearch/sql#276]
I'm currently migrating some BI reports to ElasticSearch when I stumbled upon this issue. Whenever I use more than one GROUP BYs, I can only set the size on the first aggregation (by the usage of LIMIT)

I see that this was introduced by the following removal of code due to the fact that ES 5.0 removed the support of "size": 0 term aggregations:

https://github.com/opendistro-for-elasticsearch/sql/blob/517362f68e50af5e55cd356bc1930f78d238c5d3/src/main/java/com/amazon/opendistroforelasticsearch/sql/query/AggregationQueryAction.java#L136-L140

This leads to every 2nd to nth aggregation is limited to size 10, so 
`SELECT SUM(field0), field1, field2, field3 FROM index GROUP by field1, field2, field3` 
restricts the size of `field2` and `field3` aggregations to 10 (even if there are more). Is it possible to set this number via the ES SQL API? Or can it be altered by an ElasticSearch Cluster setting?

If it's not, are there plans to make this configurable? Or perhaps set the number by default to a larger int?

**Comment by galkk** [comment]
Hi,

Thanks for feedback. I confirm the problem.

```
POST _opendistro/_sql/_explain
{
  "query": """SELECT count(*), Cancelled, OriginCountry, DestCountry, Cancelled from kibana_sample_data_flights group by Cancelled, OriginCountry, DestCountry LIMIT 10000"""
}
```

returns the following DSL
```
{
  "from" : 0,
  "size" : 0,
  "_source" : {
    "includes" : [
      "COUNT",
      "Cancelled",
      "OriginCountry",
      "DestCountry",
      "Cancelled"
    ],
    "excludes" : [ ]
  },
  "stored_fields" : [
    "Cancelled",
    "OriginCountry",
    "DestCountry",
    "Cancelled"
  ],
  "aggregations" : {
    "Cancelled" : {
      "terms" : {
        "field" : "Cancelled",
        "size" : 10000,
        "min_doc_count" : 1,
        "shard_min_doc_count" : 0,
        "show_term_doc_count_error" : false,
        "order" : [
          {
            "_count" : "desc"
          },
          {
            "_key" : "asc"
          }
        ]
      },
      "aggregations" : {
        "OriginCountry" : {
          "terms" : {
            "field" : "OriginCountry",
            "size" : 10,
            "min_doc_count" : 1,
            "shard_min_doc_count" : 0,
            "show_term_doc_count_error" : false,
            "order" : [
              {
                "_count" : "desc"
              },
              {
                "_key" : "asc"
              }
            ]
          },
          "aggregations" : {
            "DestCountry" : {
              "terms" : {
                "field" : "DestCountry",
                "size" : 10,
                "min_doc_count" : 1,
                "shard_min_doc_count" : 0,
                "show_term_doc_count_error" : false,
                "order" : [
                  {
                    "_count" : "desc"
                  },
                  {
                    "_key" : "asc"
                  }
                ]
              },
              "aggregations" : {
                "COUNT(*)" : {
                  "value_count" : {
                    "field" : "_index"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

We have plans to change to composite aggregation #174 in future.

We will investigate how good will be just bumping default size and

**Comment by subliminalvoice** [comment]
Thanks for your response. This is especially useful and necessary for BI Integration, as reports with "legacy queries" with at least 2 GROUP BYs aren't uncommon (at least in the reports I've been working on so far). I'm not sure about the implications of just bumping the default size, as I read about you can wreck your ES cluster with that number being too high. I fully support the change to composite aggregations!

**Comment by penghuo** [comment]
The issue has been fixed in new query engine (which is experimental and disabled by default). You can enable it to preview by changing the plugin setting: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled. Thanks!
