### ISSUE TITLE
chained functions in aggregation throw NullReferenceException

### ISSUE THREAD

**Issue by galkk** [opendistro-for-elasticsearch/sql#280]
```
POST _opendistro/_sql/_explain
{
  "query": """SELECT min(max(FlightDelayMin))
    from kibana_sample_data_flights
    """
}
```

throws

```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "",
    "type": "NullPointerException"
  },
  "status": 400
}
```

Even if we don't support it (now), the error message should be more clear

**Comment by chloe-zh** [comment]
Related Issue: #229

**Comment by penghuo** [comment]
> ```
> POST _opendistro/_sql/_explain
> {
>   "query": """SELECT min(max(FlightDelayMin))
>     from kibana_sample_data_flights
>     """
> }
> ```
> 
> throws
> 
> ```
> {
>   "error": {
>     "reason": "Invalid SQL query",
>     "details": "",
>     "type": "NullPointerException"
>   },
>   "status": 400
> }
> ```
> 
> Even if we don't support it (now), the error message should be more clear

The query is invalid. In MySQL 5.6,  return "Invalid use of group function". http://sqlfiddle.com/#!9/bb130f/86

The test query should be corrected as 
```
POST _opendistro/_sql/_explain?
{
  "query":"""
    SELECT SUM(AvgTicketPrice-10)
    FROM kibana_sample_data_flights
  """
}
```
The result is unexpected
```
{
  "from" : 0,
  "size" : 0,
  "_source" : {
    "includes" : [
      "SUM"
    ],
    "excludes" : [ ]
  },
  "aggregations" : {
    "SUM(AvgTicketPrice-10)" : {
      "sum" : {
        "field" : "AvgTicketPrice-10"
      }
    }
  }
}
```

**Comment by dai-chen** [comment]
The issue has been fixed in new query engine (which is experimental and disabled by default). You can enable it to preview by changing the plugin setting: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled. Thanks!
