### ISSUE TITLE
Several functions works inproperly with fieldvalue/constant parameters

### ISSUE THREAD

**Issue by chloe-zh** [opendistro-for-elasticsearch/sql#291]
Related issue: #279 

Another example:
```
POST _opendistro/_sql?format=jdbc
{
  "query" : "SELECT year(timestamp) FROM kibana_sample_data_flights limit 1"
}
```
Result:
```
{
  "schema": [{
    "name": "year_1",
    "type": "text"
  }],
  "total": 10000,
  "datarows": [[2019]],
  "size": 1,
  "status": 200
}
```

However, if the query looks like:
```
POST _opendistro/_sql?format=jdbc
{
  "query" : "SELECT year('2019-10-14T00:00:00') FROM kibana_sample_data_flights limit 1"
```
Then it doesn't work with output:
```
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "all shards failed",
    "type": "SearchPhaseExecutionException"
  },
  "status": 500
}
```

**Comment by chloe-zh** [comment]
Currently, functions ASIN, RANDOM, DATE_FORMAT, UPPER, LOWER, TRIM etc. are not working well resulted from the documentation demo from @dai-chen . In addition,I will do a double check to complete a list of functions with improper behaviors before making code changes.

**Comment by davidcui-amzn** [comment]
What is the behavior of MySql? Does it just return 2019?

**Comment by chloe-zh** [comment]
> What is the behavior of MySql? Does it just return 2019?

@davidcui-amzn Yes it is. So the thing is some functions are not supported to put a field as the input param, some are not supported to put a constant as the param. :(
