### ISSUE TITLE
multiple function calls in aggregation queries

### ISSUE THREAD

**Issue by anirudha** [opendistro-for-elasticsearch/sql#292]
eg. enabling the following query, in exploratory/design stage

SELECT DestCountry, dayOfWeek, (max(FlightDelayMin) - min(FlightDelayMin)) as diff FROM flights
    GROUP BY DestCountry, dayOfWeek

#placeholder description

**Comment by penghuo** [comment]
closed with commit.https://github.com/opendistro-for-elasticsearch/sql/commit/3730ac6e9b3a363c51432b34d2104567eb9babb7
