### ISSUE TITLE
Inaccurate results for LOG10 function

### ISSUE THREAD

**Issue by abbashus** [opendistro-for-elasticsearch/sql#297]
The results for LOG10 function are not accurate. In the below example it should be `3` instead of `2.9999....6`

```
GET /_opendistro/_sql/?format=jdbc
{
  "query": """
  SELECT FlightNum, LOG10(1000) as somealias
  FROM kibana_sample_data_flights 
 
  """
}

Result:
   [
      "2TWHRUP",
      2.9999999999999996
    ],

--------------------------------------
Similarly for raw ES result:

GET /_opendistro/_sql/?
{
  "query": """
  SELECT FlightNum, LOG10(1000) as somealias
  FROM kibana_sample_data_flights 
 
  """
}

Result:

"fields" : {
   "somealias" : [
     2.9999999999999996
   ]
 }

```

**Comment by chloe-zh** [comment]
That was because the log functions loga(b) were implemented directly using `Math.log(b)/Math.log(b)`, which introduces some inaccuracy. I went into the painless API and found it supports Math.log10, so I made a quick fix, along with LOG and LN.
