### ISSUE TITLE
Populate fields for DESCRIBE queries

### ISSUE THREAD

**Issue by jordanw-bq** [opendistro-for-elasticsearch/sql#304]
Currently, `DESCRIBE TABLES LIKE <table(s)> COLUMNS LIKE <column(s)>` only returns basic/default metadata for columns (catalog name, table name, column name, and the name of the column's type ). If possible, we would like to see more information populated by this query, so we can have one source of truth for this column metadata, rather than having to maintain and synchronize it across implementations using it (like the Open Distro JDBC driver)

Details for these metadata columns can be found here: https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlcolumns-function?view=sql-server-ver15#comments

**Comment by jordanw-bq** [comment]
The most helpful fields for ODBC driver development at the moment would be DATA_TYPE and COLUMN_SIZE. We will update this issue if we discover other fields that might come in handy earlier than others.

**Comment by dai-chen** [comment]
Duplicate as https://github.com/opendistro-for-elasticsearch/sql/issues/325 which has more context there.
