### ISSUE TITLE
关于版本问题

### ISSUE THREAD

**Issue by zhousPole** [opendistro-for-elasticsearch/sql#311]
有两个问题请教以下：
1.是否支持elasticsearch7.4.2呢？
2.还有咱这个项目是基于NLPchina/elasticsearch-sql的哪个版本？

**Comment by dai-chen** [comment]
Hi @zhousPole , 1）我们目前还没支持7.4.2，因为我们与其他OpenDistro Plugin有统一的release流程，但我们的master分支很快会先升级到7.4.2。2）我们项目是基于ES-SQL的6.3.2版本。

**Comment by dai-chen** [comment]
Release task: https://github.com/opendistro-for-elasticsearch/sql/issues/312

**Comment by zhousPole** [comment]
> Release task: #312



> Hi @zhousPole , 1）我们目前还没支持7.4.2，因为我们与其他OpenDistro Plugin有统一的release流程，但我们的master分支很快会先升级到7.4.2。2）我们项目是基于ES-SQL的6.3.2版本。



> Hi @zhousPole , 1）我们目前还没支持7.4.2，因为我们与其他OpenDistro Plugin有统一的release流程，但我们的master分支很快会先升级到7.4.2。2）我们项目是基于ES-SQL的6.3.2版本。

好的，谢谢

**Comment by dai-chen** [comment]
@zhousPole 1.4分支和master已经升级到7.4.2了：https://github.com/opendistro-for-elasticsearch/sql/tree/opendistro-1.4
