### ISSUE TITLE
es 6.3.1对应的版本是哪个呢？

### ISSUE THREAD

**Issue by donggong** [opendistro-for-elasticsearch/sql#323]
es 6.3.1对应的版本是哪个呢？亟需having功能。谢谢。

**Comment by dai-chen** [comment]
Hi @donggong , 我们项目是从支持ES 6.5.4开始的，你可以尝试将我们最老的分支版本降到6.3.1编译一下试试：https://github.com/opendistro-for-elasticsearch/sql/blob/opendistro-0.7/build.gradle#L19 。我确认了一下，HAVING已经支持：https://github.com/opendistro-for-elasticsearch/sql/blob/opendistro-0.7/src/main/java/com/amazon/opendistroforelasticsearch/sql/domain/Having.java。

**Comment by dai-chen** [comment]
我在我的分支修改了Gradle和ES的版本，但可能需要JDK 10来编译：https://github.com/dai-chen/sql/tree/build-for-es-6.3.1

**Comment by donggong** [comment]
对您的回复 表示非常的感谢。项目下周上线 非常紧急 希望您帮忙编译一下6.3.1分支 我这边也同步进行编译。

**Comment by donggong** [comment]
Gradle Version        : 4.5
  OS Info               : Linux 3.13.0-144-generic (amd64)
  JDK Version           : Oracle Corporation 10.0.1 [OpenJDK 64-Bit Server VM 10.0.1+10]
  JAVA_HOME             : /data/es/jdk-10.0.1
  Random Testing Seed   : 896535778D1B276E
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.
FAILURE: Build failed with an exception.

* Where:
Build file '/data/es/sql/build.gradle' line: 55

* What went wrong:
A problem occurred evaluating root project 'opendistro-sql'.
> Failed to apply plugin [id 'elasticsearch.esplugin']
   > Could not create task of type 'RestIntegTestTask'.

**Comment by donggong** [comment]
我用了opendistro_sql-0.7.0.0安装到了6.3.1 暂时没有发现问题。

**Comment by donggong** [comment]
root@master:/data/es/trunk/sql# ./gradlew  build -x integTestRunner dumpCoverage integTestCluster#wait

> Task :printGlobalBuildInfo UP-TO-DATE
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.6.2
  OS Info               : Linux 3.13.0-144-generic (amd64)
  JDK Version           : 12 (Oracle Corporation 12.0.1 [OpenJDK 64-Bit Server VM 12.0.1+12])
  JAVA_HOME             : /usr/java/jdk-12.0.1
  Random Testing Seed   : 83D823FFF1262844
=======================================

> Task :test
WARNING: Illegal reflective access by org.mockito.internal.creation.jmock.ClassImposterizer$3 (file:/root/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securemock/1.2/98201d4ad5ac93f6b415ae9172d52b5e7cda490e/securemock-1.2.jar) to constructor java.time.Clock()

> Task :dumpCoverage FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/data/es/trunk/sql/build-tools/sqlplugin-coverage.gradle' line: 86

* What went wrong:
Execution failed for task ':dumpCoverage'.
> java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 127.0.0.1; nested exception is: 
        java.net.ConnectException: Connection refused (Connection refused)]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
26 actionable tasks: 2 executed, 24 up-to-date

项目很赞，编译遇到问题，gradle不熟，该怎么跳过test

**Comment by chloe-zh** [comment]
Hello @donggong , 运行`./gradlew assemble`可以跳过test只获取插件的jar包，产生在`/build/distributions`目录下，但是跳过test有可能会出现些兼容性的问题。我看见你的运行日志用的是gradle v5.6.2和jdk-12.0.1，你是在使用ES v7.4.2吗？如果是，可以用我们最新的release: [v1.4.0.0](https://github.com/opendistro-for-elasticsearch/sql/releases/tag/v1.4.0.0)，我们已经解决了ES和build工具与我们插件之间兼容性的问题 ：）

**Comment by donggong** [comment]
root@master:/data/es/trunk/sql# ./gradlew build

> Task :printGlobalBuildInfo UP-TO-DATE
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.6.2
  OS Info               : Linux 3.13.0-144-generic (amd64)
  JDK Version           : 12 (Oracle Corporation 12.0.1 [OpenJDK 64-Bit Server VM 12.0.1+12])
  JAVA_HOME             : /usr/java/jdk-12.0.1
  Random Testing Seed   : D0209ADEDBEF3D5
=======================================

> Task :test
WARNING: Illegal reflective access by org.mockito.internal.creation.jmock.ClassImposterizer$3 (file:/root/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securemock/1.2/98201d4ad5ac93f6b415ae9172d52b5e7cda490e/securemock-1.2.jar) to constructor java.time.Clock()

> Task :integTestCluster#wait FAILED
> Task :dumpCoverage FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':integTestCluster#wait'.
> Failed to locate seed node transport file [/data/es/trunk/sql/build/cluster/integTestCluster node0/elasticsearch-7.4.2/logs/transport.ports]: timed out waiting for it to be created after 40 seconds

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.

版本：
root@master:/data/es/trunk/sql# git status
On branch opendistro-1.4

root@master:/data/es/trunk/sql# ls -l /data/es/trunk/sql/build/cluster/integTestCluster\ node0/elasticsearch-7.4.2/logs
total 20
-rw-r--r-- 1 root root 6818 Dec 18 17:30 gc.log
-rw-r--r-- 1 root root 2370 Dec 18 17:30 gc.log.00
-rw-r--r-- 1 root root    0 Dec 18 17:30 _integTestCluster_deprecation.json
-rw-r--r-- 1 root root    0 Dec 18 17:30 _integTestCluster_deprecation.log
-rw-r--r-- 1 root root    0 Dec 18 17:30 _integTestCluster_index_indexing_slowlog.json
-rw-r--r-- 1 root root    0 Dec 18 17:30 _integTestCluster_index_indexing_slowlog.log
-rw-r--r-- 1 root root    0 Dec 18 17:30 _integTestCluster_index_search_slowlog.json
-rw-r--r-- 1 root root    0 Dec 18 17:30 _integTestCluster_index_search_slowlog.log
-rw-r--r-- 1 root root 2715 Dec 18 17:30 _integTestCluster.log
-rw-r--r-- 1 root root 3053 Dec 18 17:30 _integTestCluster_server.json

非常感谢您的回复。我现在对这个项目非常感兴趣。会一直关注！

**Comment by ltylty** [comment]
我用0.7的分支编译，但是失败了。
```
 ./gradlew build

> Configure project :
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.10.2
  OS Info               : Linux 3.10.0-693.11.6.el7.x86_64 (amd64)
  JDK Version           : Oracle Corporation 11.0.5 [Java HotSpot(TM) 64-Bit Server VM 11.0.5+10-LTS]
  JAVA_HOME             : /home/jdk/jdk-11.0.5
  Random Testing Seed   : 4441409BBF9ED394
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/elasticsearch-sql/sql-0.7.0.0/build.gradle' line: 55

* What went wrong:
A problem occurred evaluating root project 'opendistro-sql'.
> Failed to apply plugin [id 'elasticsearch.esplugin']
   > Could not create task ':integTest'.
      > Could not create task of type 'RestIntegTestTask'.
         > Could not find method idea() for arguments [org.elasticsearch.gradle.test.RestIntegTestTask$_createCopyRestSpecTask_closure11@3e42ffb8] on root project 'opendistro-sql' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
```

**Comment by donggong** [comment]
> 我在我的分支修改了Gradle和ES的版本，但可能需要JDK 10来编译：https://github.com/dai-chen/sql/tree/build-for-es-6.3.1

你那边编译试试？我这边编译失败。

**Comment by ltylty** [comment]
@donggong 
我换成jdk10还是编译失败了。你是怎么把opendistro_sql-0.7.0.0安装到es6.3.1的啊？
```
./gradlew build

> Configure project : 
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.5
  OS Info               : Linux 4.4.0-18362-Microsoft (amd64)
  JDK Version           : Oracle Corporation 10.0.2 [Java HotSpot(TM) 64-Bit Server VM 10.0.2+13]
  JAVA_HOME             : /home/tianyuan/jdk/jdk-10.0.2
  Random Testing Seed   : 7B84841BD42D4C90
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.


FAILURE: Build failed with an exception.

* Where:
Build file '/home/tianyuan/elasticsearch-sql/sql-0.7.0.0/build.gradle' line: 55

* What went wrong:
A problem occurred evaluating root project 'opendistro-sql'.
> Failed to apply plugin [id 'elasticsearch.esplugin']
   > Could not create task of type 'RestIntegTestTask'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
```

**Comment by chloe-zh** [comment]
Hi @ltylty @donggong , ES6.3.1对应的插件版本请试试这个：[https://github.com/chloe-zh/sql/suites/366525939/artifacts/763088](https://github.com/chloe-zh/sql/suites/366525939/artifacts/763088)  希望能有用

**Comment by ltylty** [comment]
0.7版（https://github.com/opendistro-for-elasticsearch/sql/tree/opendistro-0.7）
编译成功，按官方说明即可：
1.Checkout this package from version control.
2.To build from command line set JAVA_HOME to point to a JDK >=11
3.Run ./gradlew build
注意maven仓库换成阿里的镜像，不然巨慢。
如果没成功换个环境试试，我在虚拟机里没编译成功，在win10的wsl中成功了。
如果要在elastic search6.3.1中使用。将zip包中plugin-descriptor.properties文件的elasticsearch.version改成6.3.1然后安装插件，重启es。初步测试单表的各种sql没问题，貌似having会报错。
```
{
"error": {
"root_cause": [
{
"type": "null_pointer_exception",
"reason": null
}
],
"type": "null_pointer_exception",
"reason": null
},
"status": 500
}
```
然后用dbeaver通过jdbc连接，可以像用mysql一样用es了。
这个项目太好了，希望自己后续可以贡献pr。

**Comment by ITzhangqiang** [comment]
您可以帮我编译一个7.8.1的版本吗，我这边 编译 同样遇到了 各种奇奇怪怪的问题 @chloe-zh

**Comment by chloe-zh** [comment]
> 您可以帮我编译一个7.8.1的版本吗，我这边 编译 同样遇到了 各种奇奇怪怪的问题 @chloe-zh 

你好，我建议可以用1.9.0.0版本（对应ES7.8）把es版本号从7.8.0改成7.8.1，兼容性应该挺好不太会有问题。我现在本地没有这个环境，可以的话你先试试吧，如果依旧有编译问题，我近期看看吧可以吗？

**Comment by ITzhangqiang** [comment]
> > 您可以帮我编译一个7.8.1的版本吗，我这边 编译 同样遇到了 各种奇奇怪怪的问题 @chloe-zh
> 
> 你好，我建议可以用1.9.0.0版本（对应ES7.8）把es版本号从7.8.0改成7.8.1，兼容性应该挺好不太会有问题。我现在本地没有这个环境，可以的话你先试试吧，如果依旧有编译问题，我近期看看吧可以吗？

非常感谢您的回复，我是checkout 1.13.2.0 版本，然后把es版本号改成7.8.1，报错很多。（之所以用1.13.2.0 是因为 有很多 聚合方面的新功能要使用）。这种情况有办法解决吗，可以加您微信or其他账号吗，方便及时沟通。

**Comment by chloe-zh** [comment]
> > > 您可以帮我编译一个7.8.1的版本吗，我这边 编译 同样遇到了 各种奇奇怪怪的问题 @chloe-zh
> 
> > 
> 
> > 你好，我建议可以用1.9.0.0版本（对应ES7.8）把es版本号从7.8.0改成7.8.1，兼容性应该挺好不太会有问题。我现在本地没有这个环境，可以的话你先试试吧，如果依旧有编译问题，我近期看看吧可以吗？
> 
> 
> 
> 非常感谢您的回复，我是checkout 1.13.2.0 版本，然后把es版本号改成7.8.1，报错很多。（之所以用1.13.2.0 是因为 有很多 聚合方面的新功能要使用）。这种情况有办法解决吗，可以加您微信or其他账号吗，方便及时沟通。

微信：chloez-

**Comment by chloe-zh** [comment]
@ITzhangqiang  https://github.com/chloe-zh/sql/tree/7.8.1-compatible

**Comment by chloe-zh** [comment]
[opendistro-sql-1.13.0.1.zip](https://github.com/opendistro-for-elasticsearch/sql/files/8448819/opendistro-sql-1.13.0.1.zip)
