### ISSUE TITLE
Support array type for JDBC driver

### ISSUE THREAD

**Issue by dai-chen** [opendistro-for-elasticsearch/sql#326]
Currently we return the element type instead of array in JDBC format for array. For example, long is returned for array of long. This causes JDBC driver parsing error in https://github.com/opendistro-for-elasticsearch/sql-jdbc/issues/41.

```
PUT my_index
{
  "mappings": {
     "properties":{ 
        "productId":{ 
           "type":"keyword"
        },
        "categoryIds":{ 
           "type":"long"
        }
     }
  }
}

PUT my_index/_doc/1
{
  "productId": 123456789,
  "categoryIds":  [ 567891234134123, 98765432176567 ]
}

POST _opendistro/_sql?format=jdbc
{
  "query": "select categoryIds from my_index"
}
{
  "schema": [{
    "name": "categoryIds",
    "type": "long"
  }],
  "total": 1,
  "datarows": [[[
    567891234134123,
    98765432176567
  ]]],
  "size": 1,
  "status": 200
}
```

**Comment by chloe-zh** [comment]
I ran into similar issue with null values in the resulted data rows due to JDBC not supporting array type as follows.
Data sample: `kibana_sample_data_ecommerce`
Example query:
`select products.product_name from kibana_sample_data_ecommerce limit 3`
Output:
```
{
  "schema": [{
    "name": "products.product_name",
    "type": "text"
  }],
  "total": 4675,
  "datarows": [
    [null],
    [null],
    [null]
  ],
  "size": 3,
  "status": 200
}
```
Result in csv format:
```
products.product_name,products
,"[{product_name=Basic T-shirt - dark blue/white}, {product_name=Sweatshirt - grey multicolor}]"
,"[{product_name=Denim dress - black denim}, {product_name=Shorts - black}]"
,"[{product_name=Boots - Midnight Blue}, {product_name=Short coat - white/black}]"
```

**Comment by awssenera** [comment]
@dai-chen any news on this issue is it resolved already?

**Comment by dai-chen** [comment]
Hi @awssenera Sorry this is not fixed yet. We need to prioritize and find people to work on this.

**Comment by dai-chen** [comment]
Will be tracked on issue #618. We need to figure out how to support this.
