### ISSUE TITLE
arithmetic operator should return larger type

### ISSUE THREAD

**Issue by penghuo** [opendistro-for-elasticsearch/sql#347]
## Issue
In current solution, the return type of the arithmetic operator always resolve to the type of the first argument. e.g.
```
A: Integer
B: Long
ADD(A, B) => Integer
```
## Expectation
The return type of the arithmetic operator be resolved to the larger type of the arguments. e.g.
```
A: Integer
B: Long
ADD(A, B) => Long
```

**Comment by dai-chen** [comment]
The issue has been fixed in the expression system in new query engine.

First enable new engine by https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled.

```
POST _opendistro/_sql
{  
  "query": "SELECT 1.0 + 2"
}

{
  "schema": [{
    "name": "1.0 + 2",
    "type": "double"
  }],
  "total": 1,
  "datarows": [[3]],
  "size": 1
}
```
