### ISSUE TITLE
nested queries support

### ISSUE THREAD

**Issue by xxxllluuu** [opendistro-for-elasticsearch/sql#350]
Does your team plan to support nested queries on 'sql' and 'sql-jdbc' projects?

**Comment by dai-chen** [comment]
Hi @xxxllluuu , is the nested query referring to SQL subquery or query on Elasticsearch nested field?

**Comment by xxxllluuu** [comment]
Hi @dai-chen subquery, like : "select name from (select * from user) group by name"
![微信截图_20200119143928](https://user-images.githubusercontent.com/11717369/72676218-bc499d80-3ac9-11ea-8f9a-2c68cb102547.png)

**Comment by dai-chen** [comment]
Yes, we do have limited support for subquery in FROM clause: https://github.com/opendistro-for-elasticsearch/sql/issues/230. But for now the top level query can only have SELECT-FROM. Please refer to the issue and its merged PR: https://github.com/opendistro-for-elasticsearch/sql/pull/278.

**Comment by anirudha** [comment]
please reopen if you still need help

**Comment by penghuo** [comment]
The subquery in from aleady been supported in our new engine with ODFE 1.12

* You could find the ODFE SQL 1.12 in [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#sql)
* You should enable the new engine with setting. [opendistro.sql.engine.new.enabled](https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled)
