### ISSUE TITLE
Possible to config the SQL in a standalone server to connect to an ElasticSearch server?

### ISSUE THREAD

**Issue by YouXiang-Wang** [opendistro-for-elasticsearch/sql#360]
Actually, in many cases, we may use the SAAS service provided by AWS/Azure/GCP etc. We could not install the ElasticSearch plugins freely.  So I am wondering if it is possible to config the SQL in a standalone server to connect to an ElasticSearch server?

**Comment by YouXiang-Wang** [comment]
@abbashus Do we have the plan to support this big feature?

**Comment by abbashus** [comment]
It's right now in a Elasticsearch plugin from, and thus can only be bootstrapped alongside Elasticsearch. We may in the future break down the SQL plugin functionality in a standalone consumable form.

**Comment by abbashus** [comment]
We will certainly evaluate the need for such a feature. Currently we don't have a ETA on this.

**Comment by dai-chen** [comment]
@YouXiang-Wang We've added standalone mode in our new query engine in PR https://github.com/opendistro-for-elasticsearch/sql/pull/491. You can find sample code in https://github.com/opendistro-for-elasticsearch/sql/blob/develop/integ-test/src/test/java/com/amazon/opendistroforelasticsearch/sql/ppl/StandaloneIT.java, though our engine code is not available on Maven repo yet. We will evaluate how many users need this and put efforts to make it public.
