### ISSUE TITLE
Issue building on Windows

### ISSUE THREAD

**Issue by Ultraseamus** [opendistro-for-elasticsearch/sql#361]
When trying to build this plugin I am getting several failed unit tests which all seem to have to do with unexpected carriage returns:

```
testCodeBlock
java.lang.AssertionError: 
Expected: is "Test code::\n\n\t>> curl localhost:9200\n\n"
     but: was "Test code::\r\n\r\n\t>> curl localhost:9200\r\n\r\n"
```

...

```
assertFormatterOutputsPrettyJson
java.lang.AssertionError: 
Expected: "{\r\n  \"from\" : 0,\r\n  \"size\" : 200,\r\n  \"_source\" : {\r\n    \"includes\" : [\r\n      \"firstname\"\r\n    ],\r\n    \"excludes\" : [ ]\r\n  }\r\n}"
     but: was "{\n  \"from\" : 0,\n  \"size\" : 200,\n  \"_source\" : {\n    \"includes\" : [\n      \"firstname\"\n    ],\n    \"excludes\" : [ ]\n  }\n}"
```

Is there a setting I am missing?

=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.6.2
  OS Info               : Windows 10 10.0 (amd64)
  JDK Version           : 12 (Oracle Corporation 12.0.1 [Java HotSpot(TM) 64-Bit Server VM 12.0.1+12])
  JAVA_HOME             : C:\Program Files\Java\jdk-12.0.1
  Random Testing Seed   : C3E05ADE4096F78C
=======================================

**Comment by dai-chen** [comment]
Thanks for reporting the issue! We will try to reproduce from our side. For now, you can try `./gradlew assemble` to skip unit and integration test. Reference: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/developing.rst#gradle-build

**Comment by Ultraseamus** [comment]
Thanks very much for the suggestion and the documentation link! That will unblock me for now.
