### ISSUE TITLE
Automated Documentation - Phase 3

### ISSUE THREAD

**Issue by dai-chen** [opendistro-for-elasticsearch/sql#380]
We've already prepared docs for basic usage of plugin and simple SELECT query: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/index.rst. In this phase, we want to generate more documents for what's left:

1. **DQL**
 1.1 Complex query: Subquery, JOIN, MINUS/UNION
 1.2 SHOW/DESCRIBE
 1.3 SQL Functions
2. **DML**
  2.1 DELETE
3. **Beyond SQL**
  3.1 PartiQL Compatibility
  3.2 Full Text Search
  3.3 Elasticsearch special functions

**Comment by dai-chen** [comment]
Note that SQL Functions can be generated from other type system in semantic analyzer. And there are many ES special functions in our codebase. So for these parts, we may only put basic information for now due to time limit.

**Comment by dai-chen** [comment]
Due to the time limit, docs for SQL functions only list specification for now. More descriptive information will be added in future. As for ES special functions, it takes time to figure out the spec and semantic so skip it for now too.

**Comment by anirudha** [comment]
👍 thanks
