### ISSUE TITLE
如何禁用语义分析插件？问题见详细描述

### ISSUE THREAD

**Issue by leanderli** [opendistro-for-elasticsearch/sql#383]
问题：
Caused by: com.amazon.opendistroforelasticsearch.jdbc.protocol.http.HttpException: HTTP Code: 400. Message: Bad Request. Raw response received: {
  "error": {
    "reason": "Invalid SQL query",
    "details": "Field [r_object_id1] cannot be found or used here.",
    "type": "SemanticAnalysisException"
  },
  "status": 400
}

描述：
正常的DSL的语法在查询不存在的字段时不会发生错误，尽管确实没有给出详细的问题描述；
但我也需要在查询不存在字段时正常返回，即便该字段不存在或者没有数据，我期望在ResultSet种获取时仅仅是获取到null即可；
如果直接返回该错误将导致查询无法进行；
我的系统中字段是不固定的，一个index每一个document的字段可能都不是相同的。

**Comment by dai-chen** [comment]
@leanderli 可以参考一下这里：https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-query-analysis-enabled

**Comment by leanderli** [comment]
好的，谢谢

**Comment by dai-chen** [comment]
@leanderli 不客气！另外，关于“我的系统中字段是不固定的，一个index每一个document的字段可能都不是相同的”，每当插入一个Document里有新Field时，Elasticsearch里这个Index的Mapping都会改变，我们的Semantic Analyzer取的是最新的mapping。所以你说的问题应该只发生在：你的query查询了一个Field，这个Field是在未来要插入的Document里存在时。

**Comment by leanderli** [comment]
是这样的。目前我能找到只有两种方案解决这个问题：
1、禁用Semantic Analyzer插件，禁用后除了导致错误信息不明确不知道是否会带来其他的问题？
2、当要查询一个不存在的Field之前，往mapping中插入该字段，测试过这种方式也能解决，但增加了使用成本。

**Comment by dai-chen** [comment]
好的。Semantic Analyzer只是做了更全面的语法和语义分析并提供明确的错误信息，禁用后不会有其他问题。

**Comment by leanderli** [comment]
好的。谢谢。
