### ISSUE TITLE
Function arguments missing if present in GROUP BY

### ISSUE THREAD

**Issue by chenqi0805** [opendistro-for-elasticsearch/sql#389]
Splits from #373 . Same example as #373 .

**Comment by dai-chen** [comment]
The issue has been fixed in new query engine (which is experimental and disabled by default). You can enable it to preview by changing the plugin setting: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled. Thanks!
