### ISSUE TITLE
在Java中使用JDBC驱动查询带中文条件的数据时，获取不到结果，相同SQL在Kibana中可以正确查询到数据

### ISSUE THREAD

**Issue by leanderli** [opendistro-for-elasticsearch/sql#392]
JDBC驱动版本：opendistro-sql-jdbc-1.4.0.0，
Kibana版本：opendistroforelasticseach-kibana-1.4.0，
Elasticsearch版本：opendistroforelasticsearch-1.4.0，
问题截图：
[kibana正常查询结果](https://github.com/leanderli/sql-jdbc/blob/master/docs/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20200323105103.png?raw=true)
[JDBC查询时去掉中文过滤条件的正确结果](https://github.com/leanderli/sql-jdbc/blob/master/docs/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20200323105155.png?raw=true)
[JDBC查询时加上中文过滤条件后的查询无结果返回](https://github.com/leanderli/sql-jdbc/blob/master/docs/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20200323105256.png?raw=true)

**Comment by penghuo** [comment]
多谢提交问题，可以分享一下示例数据和Mapping以便于调试。

**Comment by penghuo** [comment]
使用下面的数据集，我可以重现问题了。

```
PUT /documents/_mapping
{
  "properties": {
    "field1": {
      "type": "keyword"
    },
    "field2": {
      "type": "keyword"
    }
  }
}
PUT /documents/_doc/1
{
  "field1": "中文1",
  "field2": "test"
}
```

**Comment by penghuo** [comment]
Related issue https://github.com/opendistro-for-elasticsearch/sql-jdbc/issues/54

**Comment by penghuo** [comment]
JDBC的BUG已经修复并且合并到Master分支了。
可以同步一下JDBC的Master分支，手动编译打包一下JAR。`./gradlew clean test shadowJar`
具体的步骤可以参考JDBC文档: https://github.com/opendistro-for-elasticsearch/sql-jdbc。
这个issue我先close了，有问题再打开。

**Comment by leanderli** [comment]
测试过已经可以了，Thanks.
