### ISSUE TITLE
老版本升级问题。

### ISSUE THREAD

**Issue by zerix** [opendistro-for-elasticsearch/sql#405]
我使用的是Elasticsearch 6.6.2，安装opendistro sql插件只能装0.8.0.0版本，请问最新的1.6版本升级的功能点都没有merge到0.8.0.0版本么？

怎么解决该问题？

**Comment by penghuo** [comment]
抱歉，对于正式的发布，我们现在没有计划把新功能合并到旧的版本上。只针对安全相关的功能，我们会通过patch的方式合并到旧的版本。
如果确实需要维持Elasticsearch 6.6.2版本，我建议可以考虑自己自己修改gradle脚本，支持旧的Elasticsearch版本。

**Comment by zerix** [comment]
好的，但是mac下改grade脚本编译报错，java是12的版本。

**Comment by zerix** [comment]
好的，但是mac下改grade脚本编译报错，java是12的版本。

**Comment by zerix** [comment]
buildscript {

    ext {
        // When upgrading to version after 7.3.0, must remove also
        // project substitution from configurations.all (line 39)
        es_version = System.getProperty("es.version", "6.6.2")
    }
    // This isn't applying from repositories.gradle so repeating it here
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.elasticsearch.gradle:build-tools:${es_version}"
    }
}

编译报错信息如下

[zery@zerydeMacBook-Pro sql (master)]$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home/
[zery@zerydeMacBook-Pro sql (master)]$ ./gradlew build

> Configure project :
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 6.2.1
  OS Info               : Mac OS X 10.14.6 (x86_64)
  JDK Version           : 12 (Oracle Corporation 12.0.2 [Java HotSpot(TM) 64-Bit Server VM 12.0.2+10])
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home
  Random Testing Seed   : B9266F3E7CB241FF
=======================================

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/Users/zery/work/github/sql/build-tools/sqlplugin-coverage.gradle' line: 52

* What went wrong:
A problem occurred evaluating script.
> Could not find method runner() for arguments [sqlplugin_coverage_cvprb5pndbp2am5r1k9h0he00$_run_closure3@6fbf7e2] on task ':integTest' of type org.elasticsearch.gradle.test.RestIntegTestTask.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'opendistro-sql'.
> Failed to notify project evaluation listener.
   > Must specify license and notice file for project :
   > Must specify license and notice file for project :
   > Must specify license and notice file for project :
   > description is a required setting for esplugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s

**Comment by penghuo** [comment]
因为Elasticsearch 7.6对build系统做了不兼容改动，有些gradle task的已经没有了。可以试试修改opendistro-1.4的脚本。
另外，可以禁用sqlplugin-coverage.gradle，这个脚本只是用来提供测试覆盖报告，禁用了影响不大。

**Comment by zerix** [comment]
好的 谢谢。

**Comment by zerix** [comment]
是不是在mac下编译会有问题？不改版本直接编译会报错。
改了版本从0.9-1.4我都试过，也是报错。

**Comment by penghuo** [comment]
我们已经enable了https://github.com/opendistro-for-elasticsearch/sql/actions。
Mac编译没问题应该。

> 不改版本直接编译会报错。
能分享一下错误吗？或者./gradlew clean一下

**Comment by zerix** [comment]
我使用1.4.0的版本，./gradlew assemble 命令可以正常编译过，但是将es版本从7.4.1改成6.6.2后，就报如下错误：

17:30:14.722 [INFO] [org.gradle.api.internal.tasks.compile.JdkJavaCompiler] Compiling with JDK Java compiler API.
17:30:20.303 [ERROR] [system.err] /Users/zery/work/github/opendistro/sql/src/main/java/com/amazon/opendistroforelasticsearch/sql/domain/Having.java:36: error: cannot find symbol
17:30:20.303 [ERROR] [system.err] import static org.elasticsearch.search.aggregations.PipelineAggregatorBuilders.bucketSelector;
17:30:20.303 [ERROR] [system.err]                                                    ^
17:30:20.303 [ERROR] [system.err]   symbol:   class PipelineAggregatorBuilders
17:30:20.303 [ERROR] [system.err]   location: package org.elasticsearch.search.aggregations
17:30:20.303 [ERROR] [system.err] /Users/zery/work/github/opendistro/sql/src/main/java/com/amazon/opendistroforelasticsearch/sql/domain/Having.java:36: error: static import only from classes and interfaces
17:30:20.303 [ERROR] [system.err] import static org.elasticsearch.search.aggregations.PipelineAggregatorBuilders.bucketSelector;
17:30:20.303 [ERROR] [system.err] ^

**Comment by penghuo** [comment]
The package name in ES 6.6.2 is `org.elasticsearch.search.aggregations.pipeline`
https://github.com/elastic/elasticsearch/blob/v6.6.2/server/src/main/java/org/elasticsearch/search/aggregations/pipeline/PipelineAggregatorBuilders.java

**Comment by zerix** [comment]
> The package name in ES 6.6.2 is `org.elasticsearch.search.aggregations.pipeline`
> https://github.com/elastic/elasticsearch/blob/v6.6.2/server/src/main/java/org/elasticsearch/search/aggregations/pipeline/PipelineAggregatorBuilders.java

嗯，这些都改了之后发现，从ES 7.0开始引入了
import org.apache.lucene.search.TotalHits;
这个类，6.6.2没有。

看起来要兼容改动会很大。

**Comment by penghuo** [comment]
如果没有其他问题，我先把issue关了，有问题再开。
