### ISSUE TITLE
是否提供antlr4 grammar 文件

### ISSUE THREAD

**Issue by zerix** [opendistro-for-elasticsearch/sql#406]
为啥在源码内找不到相关文件？是否是直接共用x-pack-sql到SqlBase.g4文件？

**Comment by dai-chen** [comment]
Hi @zerix ，我们的grammar文件在这：https://github.com/opendistro-for-elasticsearch/sql/tree/master/src/main/antlr

**Comment by dai-chen** [comment]
分为lexer和parser两个文件，我们是基于https://github.com/antlr/grammars-v4/tree/master/sql/mysql/Positive-Technologies修改的。

**Comment by zerix** [comment]
谢谢。
