### ISSUE TITLE
jdbc driver could not supported select case when.

### ISSUE THREAD

**Issue by zerix** [opendistro-for-elasticsearch/sql#420]
sql plugin version: 0.8
elasticsearch: 6.6.2
jdbc driver version: 0.8

It could work when I use HTTP post SQL request with:

{
    "query": "select bookId, case when (pay < 100) then 'true' else 'false' end as label_value  from bookindex"
}

but when I use the query with jdbc SQL driver, got a exception error:

Internal Server Error. Reason: The following method is not supported in Schema: script. Type: UnsupportedOperationException. Details: java.lang.UnsupportedOperationException: The following method is not supported in Schema: script

how to fix it? update SQL plugin version?

**Comment by penghuo** [comment]
Yes, This query already been supported in our latest 1.4.0.0 version

```
PUT /bookindex/_doc/1
{
  "bookid": "123",
  "pay": 101
}

POST /_opendistro/_sql
{
  "query" : """
          select bookid, case when (pay < 100) then 'true' else 'false' end as label_value from bookindex
        """
}

{
  "schema": [
    {
      "name": "bookid",
      "type": "text"
    },
    {
      "name": "label_value",
      "type": "text"
    }
  ],
  "total": 1,
  "datarows": [[
    "123",
    "false"
  ]],
  "size": 1,
  "status": 200
}
```

**Comment by penghuo** [comment]
Close now, feel free to reopen.
