### ISSUE TITLE
Wildcard pattern on index name problem

### ISSUE THREAD

**Issue by tiagorosendo** [opendistro-for-elasticsearch/sql#422]
When I try to do a simple query like that ` SELECT * FROM index*` the plugin returns this error:
`{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "line 1:21: extraneous input '*' expecting {<EOF>, ',', 'ANALYZE', 'ANALYZED', 'AS', 'CATALOGS', 'COLUMNS', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DAY', 'DEBUG', 'EXECUTABLE', 'EXPLAIN', 'FIRST', 'FORMAT', 'FULL', 'FUNCTIONS', 'GRAPHVIZ', 'GROUP', 'HAVING', 'HOUR', 'INNER', 'INTERVAL', 'JOIN', 'LAST', 'LEFT', 'LIMIT', 'MAPPED', 'MINUTE', 'MONTH', 'NATURAL', 'OPTIMIZED', 'ORDER', 'PARSED', 'PHYSICAL', 'PIVOT', 'PLAN', 'RIGHT', 'RLIKE', 'QUERY', 'SCHEMAS', 'SECOND', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TYPE', 'TYPES', 'VERIFY', 'WHERE', 'YEAR', LIMIT_ESC, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}"
      }
    ],
    "type" : "parsing_exception",
    "reason" : "line 1:21: extraneous input '*' expecting {<EOF>, ',', 'ANALYZE', 'ANALYZED', 'AS', 'CATALOGS', 'COLUMNS', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DAY', 'DEBUG', 'EXECUTABLE', 'EXPLAIN', 'FIRST', 'FORMAT', 'FULL', 'FUNCTIONS', 'GRAPHVIZ', 'GROUP', 'HAVING', 'HOUR', 'INNER', 'INTERVAL', 'JOIN', 'LAST', 'LEFT', 'LIMIT', 'MAPPED', 'MINUTE', 'MONTH', 'NATURAL', 'OPTIMIZED', 'ORDER', 'PARSED', 'PHYSICAL', 'PIVOT', 'PLAN', 'RIGHT', 'RLIKE', 'QUERY', 'SCHEMAS', 'SECOND', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TYPE', 'TYPES', 'VERIFY', 'WHERE', 'YEAR', LIMIT_ESC, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}"
  },
  "status" : 400
}
`

I'm using a standalone installation on my elasticsearch 7.6.1 cluster. 

Am I doing something wrong?

**Comment by penghuo** [comment]
I test in my side with OpendistroSQL released 1.4.0.0 version, it works.
```
PUT /bookindex/_doc/1
{
  "bookid": "123",
  "pay": 101
}

PUT /bookxedni/_doc/1
{
  "bookid": "456",
  "pay": 99
}

POST /_opendistro/_sql
{
  "query" : """
          select * from book*
        """
}

{
  "schema": [
    {
      "name": "pay",
      "type": "long"
    },
    {
      "name": "bookid",
      "type": "text"
    }
  ],
  "total": 2,
  "datarows": [
    [
      101,
      "123"
    ],
    [
      99,
      "456"
    ]
  ],
  "size": 2,
  "status": 200
}
```
Could you share stack trace in Elasticsearch? or some sample data for reproducing the issue.

**Comment by tiagorosendo** [comment]
When I did a test with your data its works fine, but when I try with my data it did not work.

Sample data:
PUT /teste.try.rosendo-2020-03-01/_doc/2
{
  "bookid": "123",
  "pay": 101
}

PUT /teste.try.rosendo-2020-03-01/_doc/2
{
  "bookid": "123",
  "pay": 101
}

POST /_opendistro/_sql
{
  "query" : """
          select * from teste.try.rosendo*
        """
}

Returns:

{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Failed to parse query due to offending symbol [*] at: '\n          select * from teste.try*' <--- HERE... More details: extraneous input '*' expecting <EOF>",
    "type": "SyntaxAnalysisException"
  },
  "status": 400
}

**Comment by penghuo** [comment]
it was a known issue #322. 
One workaround is disable the semantic check. Then the query should work normally.
```
PUT _cluster/settings
{
  "transient" : {
    "opendistro.sql.query.analysis.enabled" : "false"
  }
}
```

**Comment by tiagorosendo** [comment]
@penghuo It worked!

Thanks for you help!
