### ISSUE TITLE
Query with order by aggregation function fails to return jdbc format output

### ISSUE THREAD

**Issue by zhongnansu** [opendistro-for-elasticsearch/sql#423]
#### Issue description
The query I tested is in [README: SQL Usage](https://github.com/opendistro-for-elasticsearch/sql/blob/master/README.md#sql-usage). It fails to return default jdbc format output.
```
SELECT COUNT(*),SUM(age),MIN(age) as m, MAX(age),AVG(age)
  FROM account
  GROUP BY gender
  HAVING m >= 20
  ORDER BY SUM(age), m DESC
```
#### Error message
```
{
  "error": {
    "reason": "Error occurred in Elasticsearch engine: all shards failed",
    "details": """Shard[0]: [account/LFh7b508QPeT_pKu8VjBEg] QueryShardException[No mapping found for [SUM(age)] in order to sort on]

For more details, please send request for Json format to see the raw response from elasticsearch engine.""",
    "type": "SearchPhaseExecutionException"
  },
  "status": 400
}
``` 
But it works fine after applying any of the following change:
1. Change to `format=json`
2. Give `SUM(age)` an alias, and `ORDER BY` its alias

#### Test data
[accounts.json](https://github.com/opendistro-for-elasticsearch/sql/blob/master/src/test/resources/doctest/testdata/accounts.json)

**Comment by dai-chen** [comment]
The issue has been fixed in new query engine (which is for now experimental and disabled by default). You can enable it to preview by changing the plugin setting: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled. Thanks!
