### ISSUE TITLE
select count(distinct age) bug.

### ISSUE THREAD

**Issue by zerix** [opendistro-for-elasticsearch/sql#439]
when I use
{
    "query": "select distinct customer_gender from kibana_sample_data_ecommerce"
}
It will be return the right result male/female.

but when I run :
{
    "query": "select count(distinct customer_gender) from kibana_sample_data_ecommerce"
}

It will return the error result:

{
  "schema": [
    {
      "name": "COUNT(customer_gender)",
      "type": "integer"
    }
  ],
  "total": 1,
  "datarows": [
    [
      4675
    ]
  ],
  "size": 1,
  "status": 200
}

I used with es 7.6.1 and SQL plugin 1.6.0.

**Comment by penghuo** [comment]
Thanks for reporting the issue.

**Comment by penghuo** [comment]
Expected Elasticsearch DSL
```
{
  "from" : 0,
  "size" : 0,
  "_source" : {
    "includes" : [
      "COUNT"
    ],
    "excludes" : [ ]
  },
  "aggregations" : {
    "COUNT_0" : {
      "cardinality" : {
        "field" : "customer_gender"
      }
    }
  }
}
```
