### ISSUE TITLE
SELECT field order ignored

### ISSUE THREAD

**Issue by kakulukia** [opendistro-for-elasticsearch/sql#44]
What i did:

    GET _opendistro/_sql?format=csv
    {
       "query": "SELECT callid,direction,fromuser,forwardedfrom,touser,start FROM cdr-2019.04.30"
    }

Whats is expected:
I expect to get a CSV with the field order of the SELECT query.

What i get instead:
I get "random" order - maybe whats defined in the index or documents .. i cant tell.

**Comment by abbashus** [comment]
Thanks for reporting , we are working on it.

**Comment by arsen-es** [comment]
Resolved by #52
