### ISSUE TITLE
group by query cannot support offset

### ISSUE THREAD

**Issue by zerix** [opendistro-for-elasticsearch/sql#441]
I used elasticsearch 7.6.1 with SQL 1.6.0

I founded that the count(*) group by query cannot support offset argment.

the query :
{
    "query": "select customer_id, count(*) as label_value from kibana_sample_data_ecommerce group by (customer_id) order by _id limit 10 offset 2"
}

the offset argument not work, it is a bug or not supported future?

**Comment by abbashus** [comment]
The plugin currently does not support offset for `GROUP BY`. We don't have a plan/ETA to add this enhancement soon.

**Comment by dheerajravindranath** [comment]
It would be great if we get this feature soon!

**Comment by dai-chen** [comment]
> It would be great if we get this feature soon!

Sure, we're planning to reimplement `GROUP BY` by ES composite aggregation API. Will evaluate this feature then. Thanks!

**Comment by dai-chen** [comment]
This issue has been fixed in our new SQL engine. Please find more details in PR above and README here: https://github.com/opendistro-for-elasticsearch/sql#experimental
