### ISSUE TITLE
SQL Query with Different Mappings

### ISSUE THREAD

**Issue by KentonParton** [opendistro-for-elasticsearch/sql#445]
When performing a SQL select query such as SELECT callId FROM txn-* LIMIT 50 the following “Invalid SQL Query” is received: “Different mappings are not allowed for the same field[msg]…”.

My question is, shouldn’t only the selected fields mappings be compared?

When the above query is executed, I would expect the mapping for “callId” across all indices matching “txn-" to be compared; however, it appears that all field mappings are being compared that match "txn-”.

Would it be possible to only compare mapping types for the selected field/s?

**Comment by abbashus** [comment]
Similar issue as #348. Don't have an ETA on this, but plan to prioritize this fix soon.

**Comment by yangjiajun2014** [comment]
I am facing same issue too.Hope u can fix soon.Thanks a lot.
