### ISSUE TITLE
date range

### ISSUE THREAD

**Issue by donggong** [opendistro-for-elasticsearch/sql#481]
I want to this:
     select count(create_date2) from xx  group by range(create_date2,'format'='yyyy-MM-dd','now-8d','now')
The create_date2 is date type.

failed

**Comment by dai-chen** [comment]
Hi @donggong, sorry for the delay. Could you post your test data and exception you saw? So we can reproduce the issue quickly.

**Comment by donggong** [comment]
I used es dsl.

**Comment by dai-chen** [comment]
Closing due to insufficient info to investigate. Feel free to reopen as needed.
