### ISSUE TITLE
Add support for queries without FROM clause

### ISSUE THREAD

**Issue by rupal-bq** [opendistro-for-elasticsearch/sql#503]
While creating extract in Tableau, the query ```SELECT NOW() as `COL` ``` is generated after getting all datarows and it fails with the following response.

Response:
```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Failed to parse query due to offending symbol [<EOF>] at: 'SELECT NOW() as `COL`' <--- HERE... More details: Expecting tokens in {'SELECT', '('}",
    "type": "SyntaxAnalysisException"
  },
  "status": 400
}
```

**Comment by dai-chen** [comment]
Sure. This would be supported in our new query engine. We are starting migration to new architecture.

Related issue: https://github.com/opendistro-for-elasticsearch/sql/issues/264
