### ISSUE TITLE
Regression? date_field>now-30d does not work in latest version

### ISSUE THREAD

**Issue by yangjiajun2014** [opendistro-for-elasticsearch/sql#508]
I use date_field>now-30d in 1.7.0.0 which works fine.But 1.8.0.0 says it is a invalid sql.

The error looks like:
Failed to parse query due to offending symbol [-30d].

**Comment by yangjiajun2014** [comment]
Change date_field>now-30d to date_field>'now-30d',it works again.

**Comment by dai-chen** [comment]
Thanks for reporting! Will investigate.

**Comment by dai-chen** [comment]
Similar issue: https://github.com/opendistro-for-elasticsearch/sql/issues/510
