### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by dai-chen** [opendistro-for-elasticsearch/sql#528]
Update development guide with our new project structure (new Gradle submodule and `./gradlew ` command changes) and Git workflow we follow (the new `develop` branch): https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/developing.rst

**Comment by dai-chen** [comment]
JDK version in README is out-of-date. Should be JDK 14+.

**Comment by dai-chen** [comment]
Need to clarify field type is `nested`: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/beyond/partiql.rst#example-employees

**Comment by Hokwang** [comment]
I am waiting this doc updates.

**Comment by Hokwang** [comment]
@dai-chen any updates?

**Comment by dai-chen** [comment]
> @dai-chen any updates?

Hi @Hokwang , I just created local branch for this. Could you let me know which update are you waiting for?

**Comment by Hokwang** [comment]
@dai-chen  it is #607.

**Comment by dai-chen** [comment]
> @dai-chen it is #607.

I see. Will try to get it updated soon. Thanks!

**Comment by Hokwang** [comment]
@dai-chen Thanks for your great doc work. but I think you need to update one more thing. https://opendistro.github.io/for-elasticsearch-docs/docs/sql/workbench/
actually I read this page at first time. I think repo is https://github.com/opendistro/for-elasticsearch-docs/.

**Comment by dai-chen** [comment]
@Hokwang thanks for reminding! yeah, that's our doc repo for all ref manual. we will push all latest doc later.
