### ISSUE TITLE
Gateway timeout

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/sql#54]
Im getting the following error when executing somewhat big querys

```
{
  "statusCode": 504,
  "error": "Gateway Time-out",
  "message": "Client request timeout"
}
```

Is there a way to extend the timeout time or force the query to run until it finish?

Thanks!

**Comment by penghuo** [comment]
> Im getting the following error when executing somewhat big querys
> 
> ```
> {
>   "statusCode": 504,
>   "error": "Gateway Time-out",
>   "message": "Client request timeout"
> }
> ```
> 
> Is there a way to extend the timeout time or force the query to run until it finish?
> 
> Thanks!

Thanks for reporting. Could you provide query for investigating?

**Comment by mporracindie** [comment]
Sure @penghuo 

```
POST /_opendistro/_sql
{
  "query": "SELECT date_format(timestamp,'Y-MM-dd'),count(*) FROM myindex group by date_format(timestamp,'Y-MM-dd')"
}
```

**Comment by penghuo** [comment]
Could u describe your cluster configuration? Do you have load balancer in front of your elasticsearch cluster? Or Do you use AWS Elasticsearch service?

**Comment by mporracindie** [comment]
@penghuo I have 4 ec2 machines working as a docker swarm where 3 of them have 2 elastic nodes of 64Gb each and the "master" has kibana and 1 64Gb node.

I can share u the docker-compose if needed.

**Comment by penghuo** [comment]
Sure, This will be helpful.
Did you run the query within kibana dev tools? If yes, there is a elasticsearch.requestTimeout in config/kibana.yml. The default value is 30s.

**Comment by mporracindie** [comment]
Changed and it worked !
I seem to keep having some issues when trying this kind of querys but i presume im having some mistakes on my side.
