### ISSUE TITLE
Upgrade to 1.9.0 wrong order of links in Kibana navigation

### ISSUE THREAD

**Issue by AlexShuraits** [opendistro-for-elasticsearch/sql#574]
Hi,

I have just upgraded the OpenDistro to 1.9.0
The order of menu items in Kibana looks wrong.
I expect the Discover to be on top, what can cause it?

![image](https://user-images.githubusercontent.com/7362416/87224576-1186ad80-c38f-11ea-84b8-df7fed1def25.png)

I am using Helm Chart with the latest Docker images.

**Comment by joshuali925** [comment]
@weicongs-amazon Kibana 7.8 orders nav by most recently installed plugins. The order changes if I install Alerting after SQL Workbench, so I don't think this is related to sql specifically. I didn't find ways to hard code the order during release, will keep looking. 

![image](https://user-images.githubusercontent.com/28062824/87482356-198c5a80-c5e6-11ea-81ba-e56dfe9798d7.png)
