### ISSUE TITLE
ODBC: Create Power BI M connector for connecting to Open Distro For Elasticsearch

### ISSUE THREAD

**Issue by rupal-bq** [opendistro-for-elasticsearch/sql#595]

**Comment by coderReview** [comment]
Hello @rupal-bq what is the roadmap for stable PowerBI connector? Thank you.

**Comment by dai-chen** [comment]
> Hello @rupal-bq what is the roadmap for stable PowerBI connector? Thank you.

Hi @anirudha , do you have the answer for this ?

**Comment by dai-chen** [comment]
Found Ani's comment on this: https://github.com/opendistro-for-elasticsearch/sql-odbc/issues/145#issuecomment-663176871
