### ISSUE TITLE
ClassCastException when combining scripts with non-script query expressions

### ISSUE THREAD

**Issue by arsen-es** [opendistro-for-elasticsearch/sql#62]
Sample query:
```sql
"SELECT balance + script('asdf','doc[\\'balance\\'].value * 2') FROM account"
```

Response:
```json
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "class com.amazon.opendistroforelasticsearch.sql.domain.MethodField cannot be cast to class com.alibaba.druid.sql.ast.SQLExpr (com.amazon.opendistroforelasticsearch.sql.domain.MethodField and com.alibaba.druid.sql.ast.SQLExpr are in unnamed module of loader java.net.FactoryURLClassLoader @46c269e0)",
    "type": "ClassCastException"
  },
  "status": 503
}
```

If you look at [SqlFunctions.java](https://github.com/opendistro-for-elasticsearch/sql/blob/d0f2e0b5a72df8094a57af2250b45460ed92ba3a/src/main/java/com/amazon/opendistroforelasticsearch/sql/utils/SQLFunctions.java#L193-L195), you'll see that all the functions try to interpret their parameters as instances of `SQLExpr`, whereas `script` gets translated to `MethodField` which is not a subclass of `SQLExpr`. For this particular query, the method name will be `add` and the 
parameters will be:
* `{SQLIdentifierExpr} "balance"`
* `{MethodField} "script(asdf,doc['balance'].value * 2)"`

**Comment by dai-chen** [comment]
Function `script` is not included in new ANTLR parser grammar so the query above will not pass now:

```
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Function [SCRIPT] cannot be found or used here. Did you mean [SQRT]?",
    "type": "SemanticAnalysisException"
  },
  "status": 400
}
```

**Comment by dai-chen** [comment]
Closing and will reopen if needed.
