### ISSUE TITLE
Is schema of use when reading from datarows

### ISSUE THREAD

**Issue by chezhiane** [opendistro-for-elasticsearch/sql#650]
opendistro-ssql -return : Is there a better way to read thru datarows
It seem to me I just need to read thru the datarows and pick for the respective field based on position.
The schema is pretty much of not use here . I am wondering if there is a better way to address the items in the datarows
based on the schema fields than position. ( i am using python to get to read thru this return)
{
  "schema": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "name",
      "type": "text"
    },
    {
      "name": "sub",
      "type": "text"
    }
  ],
  "cursor": "AAA",
  "total": 3,
  "datarows": [
    [
      3,
      "A",
      "Math"
    ],
    [
      2,
      "B",
      "Eng"
    ]
  ],
  "size": 2,
  "status": 200
}

**Comment by chloe-zh** [comment]
Hi @chezhiane thanks for reaching out. We would suggest you checkout the response with csv format, i.e. with endpoint _opendistro/_sql?format=csv

**Comment by dai-chen** [comment]
Closing due to no response. Feel free to reopen.
