### ISSUE TITLE
invalid_index_name_exception when use sql client for query documents

### ISSUE THREAD

**Issue by T10TheKinOfStars** [opendistro-for-elasticsearch/sql#664]
es version: 7.7
odfe sql: 1.8.0.0

The query works well in es 7.4.2 + sql 1.4.0.0. When upgrade to es 7.7 + odfe sql 1.8.0.0, got invalid_index_name_exception

**Comment by dai-chen** [comment]
Thanks for reporting! If you see invalid_index_name_exception for "_opendistro", I think that means the SQL plugin is not installed properly.
