### ISSUE TITLE
Is there a way to use optional parameters in query?

### ISSUE THREAD

**Issue by davide-malagoli** [opendistro-for-elasticsearch/sql#690]
Hi,

I'm trying to use the JDBC driver to connect a BI Solution we work with (TIBCO JasperSoft).
Some reports have optional parameters, and when not set these parameters are set to null.

A proper way to handle this scenario in RDBMS is creating a query like this:

SELECT <fields>
FROM <table>
WHERE ((<optional_param IS NULL) OR (<field> = <optional_param>))

So, if the parameter is not set, it will not count as a filter, otherwise it will be used against a field.

I found there's no way to achieve this with the driver, because

SELECT *
FROM <index>
WHERE NULL IS NULL

would give me parse error.

Is there any other way to handle optional parameters?

Thank you

**Comment by dai-chen** [comment]
Hi @davide-malagoli This is already fixed in new query engine. However, the new engine is disabled by default for now. You can enable it by following the instruction here: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled

**Comment by davide-malagoli** [comment]
@dai-chen Thank you, is there already any documentation of the supported features by the new sql engine?
