### ISSUE TITLE
cannot support nested select query

### ISSUE THREAD

**Issue by a2393439531** [opendistro-for-elasticsearch/sql#692]
tatementCallback; uncategorized SQLException for SQL [**SELECT
 n1
 ,
 sum(totalcount) AS 'sum(totalcount)'
 FROM (select receivedfrom.keyword as n1 ,sum(testcount) as totalcount from letters group by receivedfrom order by totalcount DESC) T
 GROUP BY n1**
 ]; SQL state [null]; error code [0]; Error executing query; nested exception is java.sql.SQLException: Error executing query

**Comment by penghuo** [comment]
With our new engine on ODFE 1.12, the issue already been solved.
* You could find the ODFE SQL 1.12 in [here](https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#sql)
* You should enable the new engine with setting. [opendistro.sql.engine.new.enabled](https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled)
