### ISSUE TITLE
Simple SQL filter query is resulting in error

### ISSUE THREAD

**Issue by kedargn** [opendistro-for-elasticsearch/sql#727]
I am new to elastic search. Here is my mapping 
```
{
  "keyword.20200828": {
    "mappings": {
      "properties": {
        "averageSimilarity": {
          "type": "float"
        },
        "body": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "cluster_type": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "domain": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
        ,"subject": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    }
  }
}
```
When I run a simple query such by hitting the REST endpoint

```
POST _opendistro/_sql
{
    "query": "SELECT domain FROM keyword.20200828 WHERE cluster_type = 'twitter.com' limit 5"
}
```

It results in following error
```
{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "runtime error",
        "script_stack": [
          "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:90)",
          "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:41)",
          "doc['keyword'].value == doc['com'].value",
          "    ^---- HERE"
        ],
        "script": "doc['keyword'].value == doc['com'].value",
        "lang": "painless",
        "position": {
          "offset": 4,
          "start": 0,
          "end": 40
        }
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "keyword.20200828",
        "node": "Fz6IBbX_TOCY55nK-o5Qng",
        "reason": {
          "type": "script_exception",
          "reason": "runtime error",
          "script_stack": [
            "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:90)",
            "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:41)",
            "doc['keyword'].value == doc['com'].value",
            "    ^---- HERE"
          ],
          "script": "doc['keyword'].value == doc['com'].value",
          "lang": "painless",
          "position": {
            "offset": 4,
            "start": 0,
            "end": 40
          },
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "No field found for [keyword] in mapping with types []"
          }
        }
      }
    ]
  },
  "status": 400
}
```
This happens only when I filter on a field which is multi-field. If I filter using single data type field such as `averageSimilarity` to filter, it works alright. 

I tried several things but I can't seem to filter based on `domain` field. I couldn't quite understand what is going wrong here. I am tried to go through other issues here. This problem is not reported. It is highly possible I have messed up something. Any help would be appreciated. Thanks!

**Comment by kedargn** [comment]
> I am new to elastic search. Here is my mapping
> 
> ```
> {
>   "keyword.20200828": {
>     "mappings": {
>       "properties": {
>         "averageSimilarity": {
>           "type": "float"
>         },
>         "body": {
>           "type": "text",
>           "fields": {
>             "keyword": {
>               "type": "keyword",
>               "ignore_above": 256
>             }
>           }
>         },
>         "cluster_type": {
>           "type": "text",
>           "fields": {
>             "keyword": {
>               "type": "keyword",
>               "ignore_above": 256
>             }
>           }
>         },
>         "domain": {
>           "type": "text",
>           "fields": {
>             "keyword": {
>               "type": "keyword",
>               "ignore_above": 256
>             }
>           }
>         }
>         ,"subject": {
>           "type": "text",
>           "fields": {
>             "keyword": {
>               "type": "keyword",
>               "ignore_above": 256
>             }
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> When I run a simple query such by hitting the REST endpoint
> 
> ```
> SELECT domain FROM keyword.20200828 WHERE cluster_type = 'twitter.com' limit 5
> ```
> 
> It results in following error
> 
> ```
> {
>   "error": {
>     "root_cause": [
>       {
>         "type": "script_exception",
>         "reason": "runtime error",
>         "script_stack": [
>           "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:90)",
>           "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:41)",
>           "doc['keyword'].value == doc['com'].value",
>           "    ^---- HERE"
>         ],
>         "script": "doc['keyword'].value == doc['com'].value",
>         "lang": "painless",
>         "position": {
>           "offset": 4,
>           "start": 0,
>           "end": 40
>         }
>       }
>     ],
>     "type": "search_phase_execution_exception",
>     "reason": "all shards failed",
>     "phase": "query",
>     "grouped": true,
>     "failed_shards": [
>       {
>         "shard": 0,
>         "index": "keyword.20200828",
>         "node": "Fz6IBbX_TOCY55nK-o5Qng",
>         "reason": {
>           "type": "script_exception",
>           "reason": "runtime error",
>           "script_stack": [
>             "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:90)",
>             "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:41)",
>             "doc['keyword'].value == doc['com'].value",
>             "    ^---- HERE"
>           ],
>           "script": "doc['keyword'].value == doc['com'].value",
>           "lang": "painless",
>           "position": {
>             "offset": 4,
>             "start": 0,
>             "end": 40
>           },
>           "caused_by": {
>             "type": "illegal_argument_exception",
>             "reason": "No field found for [keyword] in mapping with types []"
>           }
>         }
>       }
>     ]
>   },
>   "status": 400
> }
> ```
> 
> This happens only when I filter on a field which is multi-field. If I filter using single data type field such as `averageSimilarity` to filter, it works alright.
> 
> I tried several things but I can't seem to filter based on `domain` field. I couldn't quite understand what is going wrong here. I am tried to go through other issues here. This problem is not reported. It is highly possible I have messed up something. Any help would be appreciated. Thanks!

**Comment by kedargn** [comment]
Also, when I try the same query using ES DSL, it works alright

```
{
  "query": {
    "match": {
      "domain": "amazon.com"
    }
  },
  "from": 0,
  "size": 5
}
```

**Comment by kedargn** [comment]
I also tried following query:

```
select domain from `keyword`.`20200828` WHERE MATCH_QUERY(domain, 'amazon.com') LIMIT 5
```
It resulted in error:

```
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "[match] requires query value",
    "type": "IllegalArgumentException"
  },
  "status": 500
}
```

**Comment by dai-chen** [comment]
@kedargn Thanks for reporting the issue! Will investigate and update here.

**Comment by kedargn** [comment]
@dai-chen Thank you! 

I could get the same query working I do
```
curl -i -XPOST /_opendistro/_sql? -H 'Content-Type:application/json'  -d @filter_amazon.com
```
Where contents of filter_amazon.com file is 
```
{
    "query": "SELECT `domain` FROM `keyword`.`20200828` WHERE `domain` LIKE '%amazon%' LIMIT 5"
}
```
This worked!

SQL is working fine. In my first post, I think I messed up in single and double quotes in POST body.

**Comment by dai-chen** [comment]
@kedargn Cool. For your reference, here is the doc for identifiers in our new query engine: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/general/identifiers.rst#delimited-identifiers. The new engine will be enabled later once ready. Thanks!

**Comment by kedargn** [comment]
@dai-chen Do you know if multiple field in group by is supported?
This is my query
```
{
"query":"SELECT domain.keyword, subject.keyword  FROM `keyword`.`20200828` WHERE domain like '%amazon%' GROUP BY domain.keyword, subject.keyword ORDER BY domain.keyword DESC LIMIT 10"
}
```
When I try it query returns but order and limit are wrong.
```
{
  "schema": [
    {
      "name": "domain.keyword",
      "type": "double"
    },
    {
      "name": "subject.keyword",
      "type": "double"
    }
  ],
  "total": 100,
  "datarows": [
    ...... //results removed
  ],
  "size": 100,
  "status": 200
}

- It is returning 100 results when I put limit as 10.
- Sort order is not respected. I asked for descending order but I get back unsorted
- domain.keyword type is double but it is a string.

**Comment by kedargn** [comment]
I think the above group by issue might related to this issue https://github.com/opendistro-for-elasticsearch/sql/issues/174. When hit `explain` endpoint I see that aggregation is nested instead of composite

**Comment by dai-chen** [comment]
> I think the above group by issue might related to this issue #174. When hit `explain` endpoint I see that aggregation is nested instead of composite. Is there a way to enforce composite aggregation in group by?

You're right. We use Term aggregation which has problem dealing with null/missing value, pagination and result size etc. We're introducing Composite Aggregation API in new query engine. A PR would be ready next week.

**Comment by kedargn** [comment]
> > I think the above group by issue might related to this issue #174. When hit `explain` endpoint I see that aggregation is nested instead of composite. Is there a way to enforce composite aggregation in group by?
> 
> You're right. We use Term aggregation which has problem dealing with null/missing value, pagination and result size etc. We're introducing Composite Aggregation API in new query engine. A PR would be ready next week.

@dai-chen Thank you! Is there any approximate ETA when the new query engine will be released for us to download and use as docker image?

**Comment by dai-chen** [comment]
> > > I think the above group by issue might related to this issue #174. When hit `explain` endpoint I see that aggregation is nested instead of composite. Is there a way to enforce composite aggregation in group by?
> > 
> > 
> > You're right. We use Term aggregation which has problem dealing with null/missing value, pagination and result size etc. We're introducing Composite Aggregation API in new query engine. A PR would be ready next week.
> 
> @dai-chen Thank you! Is there any approximate ETA when the new query engine will be released for us to download and use as docker image?

Hi @kedargn the new query engine is already there (ODFE 1.9.0.1+ artifact or source code in `master/develop` branch). For now it's disabled by default as experimental feature. You can preview it by enabling it: https://github.com/opendistro-for-elasticsearch/sql/blob/master/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled. Thanks!

**Comment by dai-chen** [comment]
PR for introducing composite aggregation in new query engine: https://github.com/opendistro-for-elasticsearch/sql/pull/730
