### ISSUE TITLE
JOIN_CIRCUIT_BREAK_LIMIT hint impacts following requests

### ISSUE THREAD

**Issue by arsen-es** [opendistro-for-elasticsearch/sql#73]
When specifying the JOIN_CIRCUIT_BREAK_LIMIT in one of the queries. Some of the queries that run after that fail with "Memory circuit is broken" (HTTP/1.1 507: Insufficient Storage). Even if the passed value is 100 (allow 100% usage of memory). Per my understanding the hint should apply only to the query that has the hint.

Another note, even when I it to 100, it failed for a long-running query (the first one).

**Comment by dai-chen** [comment]
> When specifying the JOIN_CIRCUIT_BREAK_LIMIT in one of the queries. Some of the queries that run after that fail with "Memory circuit is broken" (HTTP/1.1 507: Insufficient Storage). Even if the passed value is 100 (allow 100% usage of memory). Per my understanding the hint should apply only to the query that has the hint.
> 
> Another note, even when I it to 100, it failed for a long-running query (the first one).

Could you provide an example so we can reproduce the issue?

**Comment by arsen-es** [comment]
See the comment on these two tests:
https://github.com/opendistro-for-elasticsearch/sql/blob/7ef4d4093c6a7aa1d655f1e15b84d15aaeaa89d0/src/test/java/com/amazon/opendistroforelasticsearch/sql/esintgtest/HashJoinIT.java#L121-L153

If you fix the code (as per comment) and run all the tests in HashJoinIT, you will observe the incorrect behavior of affecting future tests. But for the circuit breaker issue just fix the code for 1 of the tests and run it.

**Comment by dai-chen** [comment]
The hint along with old engine in legacy code is being deprecated.
