### ISSUE TITLE
support order by on SQL functions like SUM etc.

### ISSUE THREAD

**Issue by jngz-es** [opendistro-for-elasticsearch/sql#75]
select name, count(*) as count, sum(value) as sum from table group by name order by sum(value) desc limit 2;
{
  "error": {
    "root_cause": [
      {
        "type": "query_shard_exception",
        "reason": "No mapping found for [SUM(value)] in order to sort on",
        "index_uuid": "TnMD8NBgS_uZaTaR097KJg",
        "index": "table"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "table",
        "node": "FV5quMpdT9SAqMiYImQxeg",
        "reason": {
          "type": "query_shard_exception",
          "reason": "No mapping found for [SUM(value)] in order to sort on",
          "index_uuid": "TnMD8NBgS_uZaTaR097KJg",
          "index": "table"
        }
      }
    ]
  },
  "status": 400
}

**Comment by galkk** [comment]
Could you give an example of the queries that failed for you, ideally on kibana sample logs?

After recent fixes, the following queries were working fo rme
```
POST _opendistro/_sql
{
  "query" : "SELECT ip, count(*), sum(bytes) from kibana_sample_data_logs group by ip order by count(*) desc"
}

POST _opendistro/_sql
{
  "query" : "SELECT ip, count(*), sum(bytes) from kibana_sample_data_logs group by ip order by sum(bytes) desc"
}
```

**Comment by galkk** [comment]
The issue in the form that is presented is fixed. The rest of the work will be in the referenced issues
