### ISSUE TITLE
UNION queries do not work in JDBC format

### ISSUE THREAD

**Issue by theJmtz** [opendistro-for-elasticsearch/sql#752]
If I run a simple query like:
`curl -i -XPOST <hostname>:4443/_opendistro/_sql  -H 'Content-Type: application/json' -d '{"query": "select a.subject as sub from keyword.20200918 a union select b.subject as sub from keyword.20200917 b"}'`

I get the error:
```
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "",
    "type": "NullPointerException"
  },
  "status": 500
}

```
however the nearly identical query:
`curl -i -XPOST <hostname>:4443/_opendistro/_sql?format=json  -H 'Content-Type: application/json' -d '{"query": "select a.subject as sub from keyword.20200918 a union select b.subject as sub from keyword.20200917 b"}'`
works correctly.

Internally we get the following callstack for the first query:
```

"stacktrace": ["java.lang.NullPointerException: null",
"at com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.loadResultSet(Protocol.java:119) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]",
"at com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.<init>(Protocol.java:74) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]",
"at com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:80) [opendistro_sql-1.8.0.0.jar:1.8.0.0]",
"at com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:53) [opendistro_sql-1.8.0.0.jar:1.8.0.0]",
"at com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.doExecuteWithTimeMeasured(AsyncRestExecutor.java:161) [opendistro_sql-1.8.0.0.jar:1.8.0.0]",
"at com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.lambda$async$1(AsyncRestExecutor.java:121) [opendistro_sql-1.8.0.0.jar:1.8.0.0]",
"at com.amazon.opendistroforelasticsearch.sql.utils.LogUtils.lambda$withCurrentContext$0(LogUtils.java:72) [opendistro_sql-1.8.0.0.jar:1.8.0.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.7.0.jar:7.7.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]"
```

**Comment by dai-chen** [comment]
@theJmtz Thanks for reporting the issue! Unfortunately, we did have this issue: https://github.com/opendistro-for-elasticsearch/sql/issues/388. We're actively working on a new query engine to replace the old one. Please stay tune for update. Thanks!

**Comment by theJmtz** [comment]
Ah, sorry about that. I missed the comment that it was UNION queries entirely that weren't working in JDBC.

**Comment by dai-chen** [comment]
> Ah, sorry about that. I missed the comment that it was UNION queries entirely that weren't working in JDBC.

No worries! Will update here when we could reach this feature in new engine. Thanks!

**Comment by dai-chen** [comment]
Closing. Please find update on issue https://github.com/opendistro-for-elasticsearch/sql/issues/388. Thanks!
