### ISSUE TITLE
Errors in ODBC connection

### ISSUE THREAD

**Issue by Prabhu292** [opendistro-for-elasticsearch/sql#783]
Hi rupal,

I have downloaded the SQL ODBC driver from this Link : https://opendistro.github.io/for-elasticsearch/downloads.html

I am getting the error as mentioned in the screenshot.

Please help me to fix this issue.

![image](https://user-images.githubusercontent.com/72974362/96283759-4c395b00-0ffa-11eb-9eb7-a15bd743fbb4.png)

_Originally posted by @Prabhu292 in https://github.com/opendistro-for-elasticsearch/sql/issues/686#issuecomment-710173873_

**Comment by rupal-bq** [comment]
Hi @Prabhu292, 

Are you able to send request `curl -XGET http://localhost:9200` successfully? Please share logs as well. 

The error indicates some connection issue
* Server might be down
* Auth might fail
* maybe SSL issue

**Comment by Prabhu292** [comment]
Hi rupal,

Thanks a lot for your response.

Yes i am able to send the request

![image](https://user-images.githubusercontent.com/72974362/96292051-9f190f80-1006-11eb-920d-95adfc91f302.png)

I tried enabling the SSL and disabling the SSL still getting the same error.

![image](https://user-images.githubusercontent.com/72974362/96292508-fb7c2f00-1006-11eb-909a-2541af8ae384.png)


Please do let me know where to find the logs

**Comment by rupal-bq** [comment]
@Prabhu292 I am unable to reproduce this issue with 7.9.1.  Is there a specific reason for using 7.4.0?

Try sending the request `curl -XGET http://localhost:9200/_cat/plugins?format=json` and share response.

Also, for getting logs, click on Logging Options in the DSN window and set the log level to `LOG_ALL`. Set Log Path and make sure you have access to this path. Then reopen the odbc data source administrator and reproduce the issue.

**Comment by Prabhu292** [comment]
No any specific reason for 7.4.0. Actually all our data which is currently being store here. Again if we re install the new version it will be a problem.


If i type curl -XGET http://localhost:9200/_cat/plugins?format=json in the command prompt. nothing is happening. Below is the screenshot.

![image](https://user-images.githubusercontent.com/72974362/96304199-4e5ee200-1019-11eb-8e93-4c23629100ec.png)


Below is the log file. AFter testing the connection. I have disable SSL from Advance options and below is the output


 mylog.c[logs_on_off]234: mylog_on=7 qlog_on=7
	start_logging:Global.debug&commlog=7&7
   mylog.c[InitializeLogging]533: Log Output Dir: C:\logs
 es_odbc.c[DllMain]111: exe name=odbcad32
dlg_specif[CC_conninfo_init]452: entering opt=2
   setup.c[ParseAttributes]584: aszKey='DSN', value='ODFE SQL ODBC DSN'
dlg_specif[copyConnAttributes]145: key='DSN' value='ODFE SQL ODBC DSN'
dlg_specif[CC_conninfo_init]452: entering opt=3
dlg_specif[getDSNinfo]224: drivername=elasticsearchodbc
   setup.c[ParseAttributes]584: aszKey='DSN', value='ODFE SQL ODBC DSN'
dlg_specif[copyConnAttributes]145: key='DSN' value='ODFE SQL ODBC DSN'
 es_odbc.c[DllMain]118: DETACHING odfesqlodbc.dll


![image](https://user-images.githubusercontent.com/72974362/96304064-16f03580-1019-11eb-8fc8-298c10d97bb9.png)

**Comment by Prabhu292** [comment]
Forgot to post the error.

![image](https://user-images.githubusercontent.com/72974362/96305895-43598100-101c-11eb-904d-e8b6dcf6a6cc.png)

**Comment by rupal-bq** [comment]
@Prabhu292 [SQL Plugin](https://opendistro.github.io/for-elasticsearch-docs/docs/sql/) is essential for using ODBC driver. And it looks like you don't have an SQL plugin on the server. The only solution I can think of is upgrading to the version which has the SQL plugin support.

**Comment by Prabhu292** [comment]
Do you mean upgrading the version of elastic search 7.9.0?
Which version I need to install it to get the sql plug in?

**Comment by rupal-bq** [comment]
Yes, You can find all supported versions of elasticsearch [here](https://opendistro.github.io/for-elasticsearch-docs/version-history/).

Otherwise, you can just use the latest Elasticsearch version from [downloads](https://opendistro.github.io/for-elasticsearch/downloads.html).

**Comment by Prabhu292** [comment]
Thanks a lot for your patience. Much appreciated.

Surely I will upgrade the version as suggested.

**Comment by rupal-bq** [comment]
No worries. Let me know in case of any concerns.

**Comment by Prabhu292** [comment]
Hi rupal,

Sorry to bother you again.

As requested, I have updated the Elasticsearch version 7.9.1. but still getting the same error.

![image](https://user-images.githubusercontent.com/72974362/96348960-1794d480-10ca-11eb-8e40-c2766afb6968.png)

Below is the log file 

mylog.c[logs_on_off]234: mylog_on=7 qlog_on=7
	start_logging:Global.debug&commlog=7&7
   mylog.c[InitializeLogging]533: Log Output Dir: C:\logs
 es_odbc.c[DllMain]111: exe name=odbcad32
dlg_specif[CC_conninfo_init]452: entering opt=2
   setup.c[ParseAttributes]584: aszKey='DSN', value='ODFE SQL ODBC DSN'
dlg_specif[copyConnAttributes]145: key='DSN' value='ODFE SQL ODBC DSN'
dlg_specif[CC_conninfo_init]452: entering opt=3
dlg_specif[getDSNinfo]224: drivername=elasticsearchodbc
   setup.c[ParseAttributes]584: aszKey='DSN', value='ODFE SQL ODBC DSN'
dlg_specif[copyConnAttributes]145: key='DSN' value='ODFE SQL ODBC DSN'
   setup.c[test_connection]440: conn_string=DRIVER=elasticsearchodbc;server=localhost;database=elasticsearch;port=9200;UID=;PWD=;auth=NONE;region=;useSSL=0;hostnameVerification=0;logLevel=7;logOutput=C:\logs;responseTimeout=10;fetchSize=-1;
odbcapi30.[SQLAllocHandle]33: entering
 environ.c[ESAPI_AllocEnv]44: entering
 environ.c[ESAPI_AllocEnv]60: leaving phenv=000002D5061EF250
odbcapi30.[SQLSetEnvAttr]431: entering att=200,3
odbcapi30.[SQLAllocHandle]33: entering
connection[ESAPI_AllocConnect]63: entering...
connection[ESAPI_AllocConnect]66: **** henv = 000002D5061EF250, conn = 000002D506213FC0
 environ.c[EN_add_connection]502: entering self = 000002D5061EF250, conn = 000002D506213FC0
 environ.c[EN_add_connection]531:        added at 0, conn->henv = 000002D5061EF250, conns[0]->henv = 000002D5061EF250
odbcapiw.c[SQLDriverConnectW]122: entering
win_unicod[ucs2_to_utf8]126: 000000E7C7679E20 ilen=-3  newlen=196 olen=196 utf8str=DRIVER=elasticsearchodbc;server=localhost;database=elasticsearch;port=9200;UID=;PWD=;auth=NONE;region=;useSSL=0;hostnameVerification=0;logLevel=7;logOutput=C:\logs;responseTimeout=10;fetchSize=-1;
    misc.c[make_string]115: malloc size=196
    misc.c[make_string]117: str=000002D50619C8E0
dlg_specif[CC_conninfo_init]452: entering opt=2
 drvconn.c[dconn_get_attributes]223: our_connect_string = 'DRIVER=elasticsearchodbc;server=localhost;database=elasticsearch;port=9200;UID=;PWD=;auth=NONE;region=;useSSL=0;hostnameVerification=0;logLevel=7;logOutput=C:\logs;responseTimeout=10;fetchSize=-1;'
dlg_specif[getDSNinfo]224: drivername=elasticsearchodbc
 drvconn.c[dconn_get_attributes]223: our_connect_string = 'DRIVER=elasticsearchodbc;server=localhost;database=elasticsearch;port=9200;UID=;PWD=;auth=NONE;region=;useSSL=0;hostnameVerification=0;logLevel=7;logOutput=C:\logs;responseTimeout=10;fetchSize=-1;'
dlg_specif[copyConnAttributes]145: key='DRIVER' value='elasticsearchodbc'
dlg_specif[copyConnAttributes]145: key='server' value='localhost'
dlg_specif[copyConnAttributes]145: key='database' value='elasticsearch' not found
dlg_specif[copyConnAttributes]145: key='port' value='9200'
dlg_specif[copyConnAttributes]145: key='UID' value=''
dlg_specif[copyConnAttributes]121: key='PWD' value='xxxxxxxx'
dlg_specif[copyConnAttributes]145: key='auth' value='NONE'
dlg_specif[copyConnAttributes]145: key='region' value=''
dlg_specif[copyConnAttributes]145: key='useSSL' value='0'
dlg_specif[copyConnAttributes]145: key='hostnameVerification' value='0'
dlg_specif[copyConnAttributes]145: key='logLevel' value='7'
dlg_specif[copyConnAttributes]145: key='logOutput' value='C:\logs'
dlg_specif[copyConnAttributes]145: key='responseTimeout' value='10'
dlg_specif[copyConnAttributes]145: key='fetchSize' value='-1'
   mylog.c[logs_on_off]234: mylog_on=7 qlog_on=7
   mylog.c[logs_on_off]234: mylog_on=7 qlog_on=7
	start_logging:Global.debug&commlog=7&7
   mylog.c[InitializeLogging]533: Log Output Dir: C:\logs
es_communi[ESCommunication::LogMsg]793: Initializing Aws API.
es_communi[ESCommunication::LogMsg]793: Verifying connection options.
es_communi[ESCommunication::LogMsg]793: Required connection option are valid.
es_communi[ESCommunication::LogMsg]793: Starting DB connection.
es_communi[ESCommunication::LogMsg]793: Attempting to establish DB connection.
es_communi[ESCommunication::LogMsg]793: Checking for SQL plugin
es_communi[ESCommunication::LogMsg]793: 
es_communi[ESCommunication::LogMsg]793: The SQL plugin must be installed in order to use this driver. Response body: '[]'
es_communi[ESCommunication::LogMsg]793: Failed to establish connection to DB.
es_communi[ESCommunication::LogMsg]793: Dropping DB connection.
connection[CC_set_error_statements]553: entering self=000002D506213FC0
connection[CC_log_error]641: CONN ERROR: func=LIBES_connect, desc='', errnum=202, errmsg='Connection error: [Open Distro For Elasticsearch][SQL ODBC Driver][SQL Plugin] Connection error: Failed to establish connection to DB.'
connection[CC_log_error]644:             ------------------------------------------------------------
connection[CC_log_error]647:             henv=000002D5061EF250, conn=000002D506213FC0, status=0, num_stmts=16
connection[CC_log_error]649:             esconn=0000000000000000, stmts=000002D5061A5730, lobj_type=-999
es_communi[ESCommunication::LogMsg]793: Shutting down Aws API.
connection[CC_log_error]641: CONN ERROR: func=ESAPI_DriverConnect, desc='Error from CC_Connect', errnum=202, errmsg='Connection error: [Open Distro For Elasticsearch][SQL ODBC Driver][SQL Plugin] Connection error: Failed to establish connection to DB.'
connection[CC_log_error]644:             ------------------------------------------------------------
connection[CC_log_error]647:             henv=000002D5061EF250, conn=000002D506213FC0, status=0, num_stmts=16
connection[CC_log_error]649:             esconn=0000000000000000, stmts=000002D5061A5730, lobj_type=-999
odbcapi30w[SQLGetDiagRecW]197: entering
es_api30.c[ESAPI_GetDiagRec]39: entering type=2 rec=1
 environ.c[ESAPI_ConnectError]228: entering hdbc=000002D506213FC0 <512>
connection[CC_get_error]618: entering
connection[CC_get_error]630: leaving
 environ.c[ESAPI_ConnectError]245: CC_get_error: status = 202, msg = #Connection error: [Open Distro For Elasticsearch][SQL ODBC Driver][SQL Plugin] Connection error: Failed to establish connection to DB.#
 environ.c[ESAPI_ConnectError]332: 	     szSqlState = '08001',len=134, szError='Connection error: [Open Distro For Elasticsearch][SQL ODBC Driver][SQL Plugin] Connection error: Failed to establish connection to DB.'
es_api30.c[ESAPI_GetDiagRec]60: leaving 0
win_unicod[utf8_to_ucs2_lf]244: ilen=134 bufcount=512 string=Connection error: [Open Distro For Elasticsearch][SQL ODBC Driver][SQL Plugin] Connection error: Failed to establish connection to DB. ocount=134
odbcapi30.[SQLFreeHandle]219: entering
connection[ESAPI_FreeConnect]207: entering...hdbc=000002D506213FC0
connection[CC_Destructor]314: entering self=000002D506213FC0
connection[CC_cleanup]413: entering self=000002D506213FC0
connection[CC_set_error_statements]553: entering self=000002D506213FC0
connection[CC_log_error]641: CONN ERROR: func=CC_cleanup, desc='', errnum=1, errmsg='Connection not open'
connection[CC_log_error]644:             ------------------------------------------------------------
connection[CC_log_error]647:             henv=000002D5061EF250, conn=000002D506213FC0, status=0, num_stmts=16
connection[CC_log_error]649:             esconn=0000000000000000, stmts=000002D5061A5730, lobj_type=-999
connection[CC_cleanup]428: after LIBES_disconnect
dlg_specif[CC_conninfo_init]452: entering opt=1
connection[CC_cleanup]494: leaving
connection[CC_Destructor]321: after CC_Cleanup
connection[CC_Destructor]332: after free statement holders
connection[CC_Destructor]343: leaving
connection[ESAPI_FreeConnect]225: leaving...
odbcapi30.[SQLFreeHandle]219: entering
 environ.c[ESAPI_FreeEnv]69: entering env=000002D5061EF250
 environ.c[EN_Destructor]442: entering self=000002D5061EF250
 environ.c[EN_Destructor]465: clearing conns count=128
 environ.c[EN_Destructor]477: leaving rv=1
 environ.c[ESAPI_FreeEnv]72:    ok


Below is the screenshot

![image](https://user-images.githubusercontent.com/72974362/96349084-e4067a00-10ca-11eb-9d63-baa2feffea54.png)

**Comment by Prabhu292** [comment]
Hi Rupal,

I tried Downgrading the ODFC SQL driver to 1.7

![image](https://user-images.githubusercontent.com/72974362/96465602-c3632f00-1246-11eb-9b25-75835212e3ac.png)


But this time I am getting the different error.

![image](https://user-images.githubusercontent.com/72974362/96469247-a0d31500-124a-11eb-8946-83dcef18f736.png)

![image](https://user-images.githubusercontent.com/72974362/96469322-b7796c00-124a-11eb-8cdb-8cce3099267b.png)


Please help me to fix either this issue or my previous error.

**Comment by rupal-bq** [comment]
@Prabhu292 According to logs, the driver wasn't able to get SQL Plugin information.

When you send a request
```
curl -XGET http://localhost:9200/_cat/plugins?format=json
```
The response should include SQL Plugin information. For example,
```
[{"name":"RupalM-MBP.local","component":"opendistro_sql","version":"1.10.1.1"}]
```

But in this case, the driver received a response as `[]`

**Comment by Prabhu292** [comment]
Hi Rupal,

Yes you are correct. I am not getting the SQL plugin information.

Could you please suggest me how to rectify this error.

Regards,
Prabhu

**Comment by rupal-bq** [comment]
How did you set up your server? SQL plugin should be included by default. 

1. You can download the [zip](https://opendistro.github.io/for-elasticsearch-docs/docs/install/windows/#zip-install)
2. Unzip the file.
3. Open config > elasticsearch.yml and add `opendistro_security.disabled: true`
4. Open the unzipped directory at the command prompt
5. Run Open Distro for Elasticsearch. 
`.\bin\elasticsearch.bat`
6. Try sending the command `curl -XGET http://localhost:9200/_cat/plugins?format=json`.

**Comment by Prabhu292** [comment]
Hi rupa,

Thanks a lot. 

Successfully it is connected now for the local host

But instead of local host If I give the server address for example (12.12.12.12) Port number 9200 it is again getting the same error. SQL plugin issue.

Why it is not getting connecting for the Server host

**Comment by rupal-bq** [comment]
Yes, you need to configure your server accordingly.

Check the [configuration](https://opendistro.github.io/for-elasticsearch-docs/docs/install/windows/#configuration) section in Open Distro for Elasticsearch documentation.

**Comment by Prabhu292** [comment]
Thanks for the info.

I have checked the link for the configuration. 

I am little confused. 

I guess I need to change some configuration inside the elasticsearch. Yml right? 

If not could you please share me the steps to configure the server ip address. 

I am very sorry for troubling you so much. Almost I have achieved it. Only thing server thing is pending.

**Comment by rupal-bq** [comment]
Yes, change values of attributes in the Network & Discovery section in the `elasticsearch.yml` file and restart elasticsearch.
you can also use special values such as `_local_`, `_site_`, `_global_` for `network.host`.

**Comment by Prabhu292** [comment]
Hi Rupa,

As suggested, To work our server address I followed your steps . Please do let me know if it is correct. I am still unable to connect the server.

**Network Section** 

network.host: _local_, _site_, _global_

**Discovery Section**
The default list of hosts is ["127.0.0.1", "[::1]"," _local_", "_site_", "_global_",]


![image](https://user-images.githubusercontent.com/72974362/99375656-fe11c300-28e9-11eb-89cb-6ce609e592e9.png)

**Comment by Prabhu292** [comment]
And also in the Local host no data is coming in the Tableau. Please refer the screenshot.

![image](https://user-images.githubusercontent.com/72974362/99380729-577cf080-28f0-11eb-9693-149de96ebf46.png)

**Comment by rupal-bq** [comment]
What response do you get for the query `describe tables like %`?

Try sending the following request and share the response.
```
curl -XPOST http://localhost:9200/_opendistro/_sql -k -H 'Content-Type: application/json' -d '{"query": "describe tables like %"}'
```

For the host value, when you start elasticsearch, you will see the published address in logs which you can use to connect. For example,
`[2020-11-17T10:06:44,816][INFO ][o.e.h.AbstractHttpServerTransport] [RupalM-MBP.local] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}`

You can find more information [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/network.host.html)

**Comment by Prabhu292** [comment]
Below is the response in the command prompt.

![image](https://user-images.githubusercontent.com/72974362/99519182-87db9200-29b7-11eb-931f-14a49746b740.png)


Where to put this logs in the Elastic search YML file. For example if my Server elastic search Ip address is 10.12.17.182:9200

What to mention in network host and Discovery page. Could you please provide me the example in the YML file.

![image](https://user-images.githubusercontent.com/72974362/99519821-5d3e0900-29b8-11eb-9728-1cf3e75e04a0.png)

**Comment by rupal-bq** [comment]
There is no list of tables with the connection options used in Tableau. When you can send the query successfully and get a list of tables, you will see tables in Tableau as well using the same connection options.

You can find info for logs [here](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/logs/)

Also, for changing IP, you need to bind to address. You can find more info for network settings [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/modules-network.html)

**Comment by HumanAftrAll** [comment]
@rupal-bq I'm having a similar issue:

I've installed ODFE's OBDC driver on my machine and can hit the ES instance on AWS, but it returns this exception (from the log):

``` 
newlen=268 olen=268 utf8str=DRIVER=elasticsearchodbc;server=https://xxxxxxxxxxx.amazonaws.com;database=elasticsearch;port=443;UID=;PWD=;auth=NONE;region=;useSSL=0;hostnameVerification=1;logLevel=3;logOutput=C:\;responseTimeout=10;fetchSize=-1;
start_logging:Global.debug&commlog=3&3
es_communi[ESCommunication::LogMsg]793: 
es_communi[ESCommunication::LogMsg]793: The SQL plugin must be installed in order to use this driver. Response body: '[{"name":"ab_iuIZ","component":"aes_cross_cluster","version":"aes_6.8"},{"name":"ab_iuIZ","component":"alerting","version":"6.8.0"},{"name":"ab_iuIZ","component":"analysis-icu","version":"6.8.0"},{"name":"ab_iuIZ","component":"analysis-kuromoji","version":"6.8.0"},{"name":"ab_iuIZ","component":"analysis-phonetic","version":"6.8.0"},{"name":"ab_iuIZ","component":"analysis-seunjeon","version":"x.x.x.x"},{"name":"ab_iuIZ","component":"analysis-smartcn","version":"6.8.0"},{"name":"ab_iuIZ","component":"analysis-stempel","version":"6.8.0"},{"name":"ab_iuIZ","component":"analysis-ukrainian","version":"6.8.0"},{"name":"ab_iuIZ","component":"discovery-ec2","version":"6.8.0"},{"name":"ab_iuIZ","component":"elasticsearch-aes-iam","version":"6.8.0"},{"name":"ab_iuIZ","component":"elasticsearch-aes-remote-reindex","version":"1.0.0"},{"name":"ab_iuIZ","component":"elasticsearch-jetty","version":"2.2.0"},{"name":"ab_iuIZ","component":"ingest-attachment","version":"6.8.0"},{"name":"ab_iuIZ","component":"kraken","version":"unspecified"},{"name":"ab_iuIZ","component":"mapper-murmur3","version":"6.8.0"},{"name":"ab_iuIZ","component":"mapper-size","version":"6.8.0"},{"name":"ab_iuIZ","component":"opendistro-job-scheduler","version":"0.10.0"},{"name":"ab_iuIZ","component":"opendistro-sql","version":"1.0"},{"name":"ab_iuIZ","component":"opendistro_index_management","version":"0.10.0"},{"name":"ab_iuIZ","component":"opendistro_security","version":"x.x.x.x"},{"name":"ab_iuIZ","component":"performance-analyzer","version":"6.8.0"},{"name":"ab_iuIZ","component":"repository-s3","version":"6.8.0"},{"name":"ab_iuIZ","component":"sifi-remediation-plugin","version":"6.8.0"},{"name":"oIDH-8p","component":"aes_cross_cluster","version":"aes_6.8"},{"name":"oIDH-8p","component":"alerting","version":"6.8.0"},{"name":"oIDH-8p","component":"analysis-icu","version":"6.8.0"},{"name":"oIDH-8p","component":"analysis-kuromoji","version":"6.8.0"},{"name":"oIDH-8p","component":"analysis-phonetic","version":"6.8.0"},{"name":"oIDH-8p","component":"analysis-seunjeon","version":"x.x.x.x"},{"name":"oIDH-8p","component":"analysis-smartcn","version":"6.8.0"},{"name":"oIDH-8p","component":"analysis-stempel","version":"6.8.0"},{"name":"oIDH-8p","component":"analysis-ukrainian","version":"6.8.0"},{"name":"oIDH-8p","component":"discovery-ec2","version":"6.8.0"},{"name":"oIDH-8p","component":"elasticsearch-aes-iam","version":"6.8.0"},{"name":"oIDH-8p","component":"elasticsearch-aes-remote-reindex","version":"1.0.0"},{"name":"oIDH-8p","component":"elasticsearch-jetty","version":"2.2.0"},{"name":"oIDH-8p","component":"ingest-attachment","version":"6.8.0"},{"name":"oIDH-8p","component":"kraken","version":"unspecified"},{"name":"oIDH-8p","component":"mapper-murmur3","version":"6.8.0"},{"name":"oIDH-8p","component":"mapper-size","version":"6.8.0"},{"name":"oIDH-8p","component":"opendistro-job-scheduler","version":"0.10.0"},{"name":"oIDH-8p","component":"opendistro-sql","version":"1.0"},{"name":"oIDH-8p","component":"opendistro_index_management","version":"0.10.0"},{"name":"oIDH-8p","component":"opendistro_security","version":"x.x.x.x"},{"name":"oIDH-8p","component":"performance-analyzer","version":"6.8.0"},{"name":"oIDH-8p","component":"repository-s3","version":"6.8.0"},{"name":"oIDH-8p","component":"sifi-remediation-plugin","version":"6.8.0"}]'
es_communi[ESCommunication::LogMsg]793: Failed to establish connection to DB.
connection[CC_log_error]641: CONN ERROR: func=LIBES_connect, desc='', errnum=202, errmsg='Connection error: [Open Distro For Elasticsearch][SQL ODBC Driver][SQL Plugin] Connection error: Failed to establish connection to DB.'
connection[CC_log_error]644:             ------------------------------------------------------------
connection[CC_log_error]647:             henv=0000027D96D1EC10, conn=0000027D96D90980, status=0, num_stmts=16
connection[CC_log_error]649:             esconn=0000000000000000, stmts=0000027D93C866B0, lobj_type=-999
connection[CC_log_error]641: CONN ERROR: func=ESAPI_DriverConnect, desc='Error from CC_Connect', errnum=202, errmsg='Connection error: [Open Distro For Elasticsearch][SQL ODBC Driver][SQL Plugin] Connection error: Failed to establish connection to DB.'
connection[CC_log_error]644:             ------------------------------------------------------------
connection[CC_log_error]647:             henv=0000027D96D1EC10, conn=0000027D96D90980, status=0, num_stmts=16
connection[CC_log_error]649:             esconn=0000000000000000, stmts=0000027D93C866B0, lobj_type=-999
 environ.c[ESAPI_ConnectError]228: entering hdbc=0000027D96D90980 <512>
 environ.c[ESAPI_ConnectError]245: CC_get_error: status = 202, msg = #Connection error: [Open Distro For Elasticsearch][SQL ODBC Driver][SQL Plugin] Connection error: Failed to establish connection to DB.#
```

`SQL Plugin` is installed on the instance and checking `Enable SSL` on advanced options has no effect.

The instance's info:
```
{
  "name": "xxxxx",
  "cluster_name": "xxxxxxx",
  "cluster_uuid": "xxxxxx",
  "version": {
    "number": "6.8.0",
    "build_flavor": "oss",
    "build_type": "zip",
    "build_hash": "Unknown",
    "build_date": "2020-11-03T10:33:44.805967Z",
    "build_snapshot": false,
    "lucene_version": "7.7.0",
    "minimum_wire_compatibility_version": "5.6.0",
    "minimum_index_compatibility_version": "5.0.0"
  },
  "tagline": "You Know, for Search"
}
```

One thing that got my attention is that the exception tells me that the `SQL Plugin` is needed, even though it's already installed on the instace. 

If you need, I can move open a new issue for my question only.

Thanks!

**Comment by deric4** [comment]
Having the same problem  as @HumanAftrAll  on Amazon Elasticsearch Service for a few days now, and it looks like it might be related to #1078  where the driver is looking for `opendistro-sql` but the cluster has `opendistro_sql`.

It doesn't seem possible to check the version of the plugin being used on the cluster:

```jsonc
[
  // ... removed other plugins for brevity
  {
    "name": "<name>",
    "component": "opendistro-anomaly-detection",
    "version": "x.x.x.x"
  },
  {
    "name": "<name>",
    "component": "opendistro-job-scheduler",
    "version": "x.x.x.x"
  },
  {
    "name": "<name>",
    "component": "opendistro-knn",
    "version": "x.x.x.x"
  },
  {
    "name": "<name>",
    "component": "opendistro-reports-scheduler",
    "version": "x.x.x.x"
  },
  {
    "name": "<name>",
    "component": "opendistro_index_management",
    "version": "x.x.x.x"
  },
  {
    "name": "<name>",
    "component": "opendistro_security",
    "version": "x.x.x.x"
  },
  {
    "name": "<name>",
    "component": "opendistro_sql",
    "version": "x.x.x.x"
  },
  {
    "name": "<name>",
    "component": "performance-analyzer",
    "version": "7.9.1"
  },
  {
    "name": "<name>",
    "component": "repository-s3",
    "version": "7.9.1"
  },
  {
    "name": "<name>",
    "component": "sifi-remediation-plugin",
    "version": "7.9.1"
  }
]
```

I was hoping to try downgrading the ODBC driver version to `1.12.x` to see if that helped, but wasn't able to find it on the downloads page: https://opendistro.github.io/for-elasticsearch/downloads.html#all

This is the most commented open issue for the project and now that AWS has announced support today, any chance some additional trouble shooting steps could be added to the documentation?

https://aws.amazon.com/about-aws/whats-new/2021/04/amazon-elasticsearch-service-now-supports-integration-with-microsoft-power-bi/

**Comment by Arpitha387** [comment]
Hi All,

I have downloaded  ODFC SQL driver to 1.7 and ES is 7.11.0 version .
Still am getting error while connecting i through DSN 
![image](https://user-images.githubusercontent.com/87110280/124865370-2749a580-dfd8-11eb-837c-7ab5a8d1a7f3.png)


Please help me to fix this issue.

**Comment by dharminfadia** [comment]
> ![image](https://user-images.githubusercontent.com/72974362/96305895-43598100-101c-11eb-904d-e8b6dcf6a6cc.png)

**Hello guyes I am having same issue with latest version with OpenDistro and opensearch both cluster kindly help what I have to do plase suggest with excet step by step and I dont want to disable SSL for Client Connection in elasticsearch.yml or opensearch.yml  Waiting for Quick Response**
