### ISSUE TITLE
这个插件支持 elasticsearch 7.8.1基础版本嘛

### ISSUE THREAD

**Issue by withlw** [opendistro-for-elasticsearch/sql#787]

**Comment by anirudha** [comment]
Yes, but we have built the plugin for it. it's a easy build if you want to try from 7.8 branch.

Version information is here : https://github.com/opendistro-for-elasticsearch/sql/issues/787

 Please  use this for questions. Thanks!

https://discuss.opendistrocommunity.dev/c/sql/8
