### ISSUE TITLE
Boolean fields. amazon/opendistro-for-elasticsearch:1.11.0

### ISSUE THREAD

**Issue by bralbral** [opendistro-for-elasticsearch/sql#811]
Hello! 

![image](https://user-images.githubusercontent.com/54455457/98446809-55b56f00-2131-11eb-83ab-48a1a0990d24.png)

Boolean fields are not displayed. 

What is the problem? 

Best regards!

**Comment by dai-chen** [comment]
Thanks for reporting the issue! Will investigate.

**Comment by dai-chen** [comment]
@bralbral We've reproduced the issue from our side. Will investigate the root cause. Thanks!

**Comment by bralbral** [comment]
@dai-chen Thank you for quick response !

**Comment by dai-chen** [comment]
Confirmed that SQL plugin can return bool field without issue. Need to find the root cause in Workbench code.

**Comment by dai-chen** [comment]
This has been fixed in https://github.com/opendistro-for-elasticsearch/sql/issues/813
