### ISSUE TITLE
Rows count

### ISSUE THREAD

**Issue by bralbral** [opendistro-for-elasticsearch/sql#825]
Hello! Thanks a lot for the plugin! I ran into some difficulties when using it. I am trying to get strings by query from **clickhouse** using **JDBC** engine. But at the same time, the number of lines in the select is always 200. What is this connected with? As I understand it, the **search api** is used instead of the **scroll api**.
Thanks!

**Comment by anirudha** [comment]
Use sql cursors for scroll api. The default results returned limit is 200. Use **SQL LIMIT** clause to get more data.
