### ISSUE TITLE
wildcard field type  amazon/opendistro-for-elasticsearch:1.11.0

### ISSUE THREAD

**Issue by bralbral** [opendistro-for-elasticsearch/sql#832]
Hello! 

An error occurs when displaying wildcard fields. In this case, you can search in the field itself, if it is not displayed to the user
[https://www.elastic.co/guide/en/elasticsearch/reference/master/keyword.html#wildcard-field-type](url)

Will such support be introduced? Very often it makes sense to store data in such a field, since it optimizes the query speed.

Best regards!

**Comment by dai-chen** [comment]
@bralbral Thanks for reporting the issue! I notice that this wildcard field feature is offered in Elastic x-pack. Will confirm but most likely we cannot support this.

**Comment by bralbral** [comment]
Thank you for quick response!

Yes you are right, this is from xpack. For a start, it would be great if this would render the fields. We now need to store field values ​​in two fields: a keyword and a wildcard. We search in  wildcard field and after show for user keyword field.

**Comment by anirudha** [comment]
How do I replicate the issue can you include sample query here. Thanks

**Comment by bralbral** [comment]
@anirudha Thank you!

1. Elasticsearch with basic license and installed sql plugin : [https://github.com/bralbral/elasticsearch-kibana](url)
2. Create index template with wildcard field:
[PUT _index_template/testing
{
  "template": {
    "mappings": {
      "properties": {
        "field1": {
          "type": "wildcard"
        },
        "field2": {
          "type": "keyword"
        }
      }
    }
  },
  "index_patterns": [
    "test*"
  ]
}](url)
3. Fill it with some data:
```
POST test1/_doc/
{
  "field1": "testing",
  "field2": "testing"

}

POST test1/_doc/
{
  "field1": "blahblahblah",
  "field2": "some data"

}
```
4. Open Query workbench : [http://localhost:5601/app/opendistro-query-workbench](url)
5. Execute `select field1, field2 from test1, where field1 is **wildcard** type`
![image](https://user-images.githubusercontent.com/54455457/99443965-99c42300-292c-11eb-9fda-d2f4da7e4dec.png)
6.  Execute `select  field2 from test1`
![image](https://user-images.githubusercontent.com/54455457/99444077-c37d4a00-292c-11eb-822f-3360896d97d7.png)
7. Execute `select  field2 from test1 where field1 like '%test%'`
![image](https://user-images.githubusercontent.com/54455457/99444161-e4de3600-292c-11eb-9310-b896aa71c495.png)

Please write whether you managed to reproduce the error. 

Best regards!

**Comment by bralbral** [comment]
Good day! Any news on this? Should I wait for a fix?
