### ISSUE TITLE
Double quote is unsupported

### ISSUE THREAD

**Issue by nkavian** [opendistro-for-elasticsearch/sql#874]
When trying this command `SELECT * FROM objects WHERE _object="Event" LIMIT 4;` I get `Objects: no response`;

But when trying `SELECT * FROM objects WHERE _object='Event' LIMIT 4;`, it works fine.

If double quotes are not supported, the error message should match accordingly.

**Comment by dai-chen** [comment]
@nkavian Thanks for reporting the issue! We don't support double quotes in legacy engine. In new SQL engine, double quoted text is treated as identifier: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/general/identifiers.rst#delimited-identifiers.

We may support MySQL-like ANSI_MODE so you can configure if double quotes are for literal or identifier. Need to evaluate this.

**Comment by nkavian** [comment]
Understood, it's okay if double quotes are not supported. I'm hoping that the error message could be more descriptive. Also, when I tried searching the [documentation](https://opendistro.github.io/for-elasticsearch-docs/) for `double quotes`, I didn't find anything that could help me understand what kind of quotes were supported. So my first experience using this plugin was difficult. Thanks.

**Comment by dai-chen** [comment]
> Understood, it's okay if double quotes are not supported. I'm hoping that the error message could be more descriptive. Also, when I tried searching the [documentation](https://opendistro.github.io/for-elasticsearch-docs/) for `double quotes`, I didn't find anything that could help me understand what kind of quotes were supported. So my first experience using this plugin was difficult. Thanks.

@nkavian Thanks for your feedback! We've improved the error message for Run/Explain in Workbench here: https://github.com/opendistro-for-elasticsearch/sql/pull/872. Closing this issue. Feel free to reopen if needed. Thanks!
