### ISSUE TITLE
Elasticsearch 7.1.1 compatibility

### ISSUE THREAD

**Issue by arsen-es** [opendistro-for-elasticsearch/sql#90]
Make the plugin compatible with Elasticsearch 7.1.1

**Comment by hyperbaba** [comment]
Any chance to have ES 7.2 version build?

**Comment by dai-chen** [comment]
> Any chance to have ES 7.2 version build?

Hi! I just created an issue for this: https://github.com/opendistro-for-elasticsearch/sql/issues/125. We will try to add the support later.

**Comment by dai-chen** [comment]
@hyperbaba It's been merged. You can check it out if you like: https://github.com/opendistro-for-elasticsearch/sql/issues/125
