### ISSUE TITLE
Alias working only in some cases, and other inconsistencies

### ISSUE THREAD

**Issue by FreCap** [opendistro-for-elasticsearch/sql#935]
I noticed that when using alias, it seems that there are a few different response patterns, while we should probably just have one:

**Pattern 1:**:  SELECTING only one alias --> UNEXPECTED
```

POST _opendistro/_sql?format=json
{
  "query": "SELECT YEAR(Birthday) as yearAlias FROM my_index LIMIT 100"
}

    "hits" : [
      {
        "_index" : "my_index ",
        "_type" : "_doc",
        "_id" : "urn:123",
        "_score" : 1.0,
        "_source" : {
          "entity_id" : "urn:123",
          "last_update" : "2020-11-22T11:32:24.589219+00:00",
          ########## ALL FIELDS even if we didn't requested them! ##########
        },
        "fields" : {
          "yearAlias" : [
            2017
          ]
        }
      },
.... others...

```

**Pattern 2:**:  SELECTING one alias and one field --> EXPECTED

```

POST _opendistro/_sql?format=json
{
  "query": "SELECT Birthday, YEAR(Birthday) as yearAlias FROM my_index LIMIT 100"
}

    "hits" : [
      {
        "_index" : "my_index ",
        "_type" : "_doc",
        "_id" : "urn:123",
        "_score" : 1.0,
        "_source" : {
          "Birthday" : "2017-01-02"
        },
        "fields" : {
          "yearAlias" : [
            2017
          ]
        }
      },
.... others...

```

**Pattern 3:**:  SELECTING one plain field as alias --> UNEXPECTED

```

POST _opendistro/_sql?format=json
{
  "query": "SELECT Birthday as birthdayAlias FROM my_index LIMIT 100"
}

    "hits" : [
      {
        "_index" : "my_index ",
        "_type" : "_doc",
        "_id" : "urn:123",
        "_score" : 1.0,
        "_source" : {
          "Birthday" : "2017-01-02"
        },
/****** EXPECTED A `FIELDS` field but it is not here (a field like the one below) 
        "fields" : {
          "birthdayAlias " : [
            2017
          ]
        }
******** NOT HERE ***************/
      },
.... others...

```

Hope the report can help the dev! 
If you know which files should be changed, please feel free to comment

**Comment by dai-chen** [comment]
@FreCap Thanks for reporting the issue! Did you see this issue in default (JDBC) format? Any reason you want to access original DSL in JSON format? And we encourage you to try out our new SQL engine: https://github.com/opendistro-for-elasticsearch/sql#experimental. We're working hard on it and will deprecate the legacy one once ready. Thanks!

**Comment by FreCap** [comment]
Thanks @dai-chen, the JDBC version works!
By default I'm using the json-es version for backward compatibility since my system is running some "ACL column level" checks  on the ES-response schema.

I could think of contributing the ACL system in the language if you think it might be interesting for the community.

E.g.

`SELECT a,b,c,d FROM index SHADOW_ACCESS_TO e,f,g    --> run succesfully`

`SELECT a,b,c,d FROM index SHADOW_ACCESS_TO b.innserField    --> returns result shadowing b`
`SELECT a,b,c,d FROM index SHADOW_ACCESS_TO b.innserField    --> returns result shadowing b.innerField, returns the rest of b`

The use case of this feature is allowing end users (e.g. data scientists), plugging in a "WHERE" and "SELECT" conditions in free form and the engine can just append the fields they are forbidden to access (or whitelist if we want).

I'd be happy to have a quick 15min chat on this also on Zoom if your schedule allows

**Comment by dai-chen** [comment]
@FreCap Just came back from vacation this week. Sorry for the delay! 

For your info, we're going to deprecate legacy engine and promote the improved SQL engine: https://github.com/opendistro-for-elasticsearch/sql#experimental. Because this will happen in near future, I would suggest you migrate to our default (JDBC format) in this new SQL engine.

No worries if you want to stick with the old engine, it will still work for you after deprecation. Any contribution to old engine is welcomed. Thanks!
