### ISSUE TITLE
high opendistro/_sql version （1.7.0.0） doesn't support Date  MAX

### ISSUE THREAD

**Issue by bigfishman** [opendistro-for-elasticsearch/sql#953]

**Comment by chloe-zh** [comment]
Did you mean max aggregation? v1.7.0.0 should have supported max aggregation, could you provide a sample query and a couple of lines of sample data with mappings?

**Comment by bigfishman** [comment]
when i execute sql like this  in  es  7.6.2 and  opendistro sql 1.7.0.0
`POST testindex/_doc
{
  "age":1244,
    "updated_at" : "2020-12-22T09:45:26.928Z"
}


POST testindex/_doc
{
  "age":12456,
    "updated_at" : "2020-12-22T09:55:26.928Z"
}


POST testindex/_doc
{
  "age":63,
    "updated_at" : "2020-12-22T09:35:26.928Z"
}

POST _opendistro/_sql
{
  "query":"select MAX(updated_at) from testindex"
}

`
error  like this 

'{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Function [MAX] cannot work with [DATE]. Usage: MAX(NUMBER T) -> T",
    "type": "SemanticAnalysisException"
  },
  "status": 400
}'


when  i use  1.1.0.0  and es 7.1.1   it works.

**Comment by chloe-zh** [comment]
Thanks for providing the examples. 

That's because we added a semantic check before executing the query, and it failed semantic check because the date aggregation might be not fully supported yet in the old engine. 

Fortunately we have supported date aggregation in our new engine, you can enable the new engine with the following setting:
```
curl -X PUT localhost:9200/_opendistro/_sql/settings -H 'Content-Type: application/json' -d '
{
  "transient": {
    "opendistro.sql.engine.new.enabled": "true"
  }
}'
```

Another option is to turn off the semantic analyzer to bypass the check so the query will be executed directly, since you mentioned the earlier version works. You can disable the semantic analysis with the following setting:
```
curl -X PUT localhost:9200/_opendistro/_sql/settings -H 'Content-Type: application/json' -d '
{
  "transient": {
    "opendistro.sql.query.analysis.enabled": "false"
  }
}'

```

For more details, please see the user manual: https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/admin/settings.rst

**Comment by bigfishman** [comment]
Thank you very much, I didn’t realize this semantic check can be turned off like this,

**
curl -X PUT localhost:9200/_opendistro/_sql/settings -H 'Content-Type: application/json' -d '
{
  "transient": {
    "opendistro.sql.query.analysis.enabled": "false"
  }
}'
**
This really helped me solve the problem

and  set the opendistro.sql.engine.new.enabled it seems to provide in 1.9.0.0 , it doesn’t work in 1.7.0.0 , i will try in my es 7.9.3 with 1.11.0.0 opendistro

thanks again, this problem is solved.

**Comment by xiaohaifirst** [comment]
1.7.0.0不是只适配7.6.1的么，请问兄台怎么编译成7.6.2的版本呀，我改了build.gradle中的7.6.1---->7.6.2发现构建报错。

**Comment by xiaohaifirst** [comment]
> when i execute sql like this in es 7.6.2 and opendistro sql 1.7.0.0
> `POST testindex/_doc
> {
> "age":1244,
> "updated_at" : "2020-12-22T09:45:26.928Z"
> }
> 
> POST testindex/_doc
> {
> "age":12456,
> "updated_at" : "2020-12-22T09:55:26.928Z"
> }
> 
> POST testindex/_doc
> {
> "age":63,
> "updated_at" : "2020-12-22T09:35:26.928Z"
> }
> 
> POST _opendistro/_sql
> {
> "query":"select MAX(updated_at) from testindex"
> }
> 
> `
> error like this
> 
> '{
> "error": {
> "reason": "Invalid SQL query",
> "details": "Function [MAX] cannot work with [DATE]. Usage: MAX(NUMBER T) -> T",
> "type": "SemanticAnalysisException"
> },
> "status": 400
> }'
> 
> when i use 1.1.0.0 and es 7.1.1 it works.

1.7.0.0不是只适配7.6.1的么，请问兄台怎么编译成7.6.2的版本呀，我改了build.gradle中的7.6.1---->7.6.2发现构建报错。
