### ISSUE TITLE
Support SELECT 1 or similar

### ISSUE THREAD

**Issue by dpgaspar** [opendistro-for-elasticsearch/sql#994]
Hi,

I'm currently building support for opendistro SQL on sqlalchemy (currently only Elastic elasticsearch is supported):
https://github.com/preset-io/elasticsearch-dbapi

One function that is supported by a SQLAlchemy dialect is `do_ping`, this is normally done by issuing a `SELECT 1`, since opendistro does not support `SELECT 1` can you help with a similar statement for `do_ping`?

Thank you

**Comment by dai-chen** [comment]
Hi @dpgaspar, thanks for reporting the issue! This is already supported in our new SQL query engine. For now it's disabled by default and will be enabled in future release. Please find more details here: https://github.com/opendistro-for-elasticsearch/sql#experimental. To make your work easier, I suggest you start working with our new engine. If you get any issue in future, feel free to contact us. Thanks!

**Comment by dpgaspar** [comment]
Will try it out then, I was able to implement these missing features. It's probably better for now to support the non experimental version. When it becomes oficial I'll remove the custom implementation

**Comment by dpgaspar** [comment]
Hi just tried out on AWS ES 7.9

```
$ curl -XPUT https://username:password@cluster.us-west-2.es.amazonaws.com:443/_opendistro/_sql/settings -H 'Content-Type: application/json' -d '
{
    "transient" : {
        "opendistro.sql.engine.new.enabled" : "true" }
}'
{"acknowledged":true,"persistent":{},"transient":{"opendistro":{"sql":{"engine":{"new":{"enabled":"true"}}}}}} 

$ curl -XPOST https://username:password@cluster.us-west-2.es.amazonaws.com:443/_opendistro/_sql\?format\=json -H 'Content-Type: application/json' -d '
{
    "query" :
        "select 1"
}'
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Failed to parse query due to offending symbol [<EOF>] at: 'select 1' <--- HERE... More details: Expecting tokens in {'SELECT', '('}",
    "type": "SyntaxAnalysisException"
  },
  "status": 400
}%
```

**Comment by dai-chen** [comment]
Hi @dpgaspar , the new engine is disabled by default in AES. From what you posted, you enabled it but the problem was in your request `format=json`. The new engine doesn't support json format any more so you request was still handled by old engine due to fallback mechanism.

For your info, we're turned on new engine in `develop` branch. Next we will roll it out in next ODFE and AES release. Thanks!

**Comment by dpgaspar** [comment]
ok makes sense now, I really appreciate your support. 

Again I'll finish the implementation of the dbapi for the old engine, and make the migration after the new engine get's to AWS

**Comment by dai-chen** [comment]
> ok makes sense now, I really appreciate your support.
> 
> Again I'll finish the implementation of the dbapi for the old engine, and make the migration after the new engine get's to AWS

Cool. Will keep you updated. Thanks!
